// Code generated by ent, DO NOT EDIT.

package publicimageinteraction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldUpdatedAt, v))
}

// ImageID applies equality check predicate on the "image_id" field. It's identical to ImageIDEQ.
func ImageID(v uuid.UUID) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldImageID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldUserID, v))
}

// Liked applies equality check predicate on the "liked" field. It's identical to LikedEQ.
func Liked(v bool) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldLiked, v))
}

// Favorited applies equality check predicate on the "favorited" field. It's identical to FavoritedEQ.
func Favorited(v bool) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldFavorited, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldLTE(FieldUpdatedAt, v))
}

// ImageIDEQ applies the EQ predicate on the "image_id" field.
func ImageIDEQ(v uuid.UUID) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldImageID, v))
}

// ImageIDNEQ applies the NEQ predicate on the "image_id" field.
func ImageIDNEQ(v uuid.UUID) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldNEQ(FieldImageID, v))
}

// ImageIDIn applies the In predicate on the "image_id" field.
func ImageIDIn(vs ...uuid.UUID) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldIn(FieldImageID, vs...))
}

// ImageIDNotIn applies the NotIn predicate on the "image_id" field.
func ImageIDNotIn(vs ...uuid.UUID) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldNotIn(FieldImageID, vs...))
}

// ImageIDGT applies the GT predicate on the "image_id" field.
func ImageIDGT(v uuid.UUID) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldGT(FieldImageID, v))
}

// ImageIDGTE applies the GTE predicate on the "image_id" field.
func ImageIDGTE(v uuid.UUID) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldGTE(FieldImageID, v))
}

// ImageIDLT applies the LT predicate on the "image_id" field.
func ImageIDLT(v uuid.UUID) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldLT(FieldImageID, v))
}

// ImageIDLTE applies the LTE predicate on the "image_id" field.
func ImageIDLTE(v uuid.UUID) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldLTE(FieldImageID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldLTE(FieldUserID, v))
}

// LikedEQ applies the EQ predicate on the "liked" field.
func LikedEQ(v bool) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldLiked, v))
}

// LikedNEQ applies the NEQ predicate on the "liked" field.
func LikedNEQ(v bool) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldNEQ(FieldLiked, v))
}

// FavoritedEQ applies the EQ predicate on the "favorited" field.
func FavoritedEQ(v bool) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldEQ(FieldFavorited, v))
}

// FavoritedNEQ applies the NEQ predicate on the "favorited" field.
func FavoritedNEQ(v bool) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.FieldNEQ(FieldFavorited, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PublicImageInteraction) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PublicImageInteraction) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PublicImageInteraction) predicate.PublicImageInteraction {
	return predicate.PublicImageInteraction(sql.NotPredicates(p))
}
