package errs

const (
	CodeInternal                      = "INTERNAL_ERROR"
	CodeBadRequest                    = "BAD_REQUEST"
	CodeMethodNotAllowed              = "METHOD_NOT_ALLOWED"
	CodeUnauthorized                  = "UNAUTHORIZED"
	CodeForbidden                     = "FORBIDDEN"
	CodeNotFound                      = "NOT_FOUND"
	CodeConflict                      = "CONFLICT"
	CodeRateLimited                   = "RATE_LIMITED"
	CodeValidationFailed              = "VALIDATION_FAILED"
	CodeAuthAccessExpired             = "AUTH_ACCESS_EXPIRED"
	CodeAuthRefreshExpired            = "AUTH_REFRESH_EXPIRED"
	CodeAuthRefreshReplayBlocked      = "AUTH_REFRESH_REPLAY_BLOCKED"
	CodeUserDisabled                  = "USER_DISABLED"
	CodeAPIKeyDisabled                = "API_KEY_DISABLED"
	CodeInsufficientPoints            = "BILLING_INSUFFICIENT_POINTS"
	CodeModelRouteNotFound            = "MODEL_ROUTE_NOT_FOUND"
	CodeModelRouteNotVisible          = "MODEL_ROUTE_NOT_VISIBLE"
	CodeModelRouteNoCandidate         = "MODEL_ROUTE_NO_CANDIDATE"
	CodeRouteModelPriceMissing        = "ROUTE_MODEL_PRICE_MISSING"
	CodeImageCapabilityMismatch       = "IMAGE_CAPABILITY_MISMATCH"
	CodeImageReferenceRequired        = "IMAGE_REFERENCE_REQUIRED"
	CodeImageReferenceExceeded        = "IMAGE_REFERENCE_COUNT_EXCEEDED"
	CodeImageAutoUnsupported          = "IMAGE_AUTO_RESOLUTION_UNSUPPORTED"
	CodeImageTaskFailed               = "IMAGE_TASK_FAILED"
	CodeImageStorageFailed            = "IMAGE_STORAGE_FAILED"
	CodeUpstreamUnavailable           = "UPSTREAM_UNAVAILABLE"
	CodeUpstreamBadRequest            = "UPSTREAM_BAD_REQUEST"
	CodeContentBlocked                = "UPSTREAM_CONTENT_BLOCKED"
	CodePaymentMethodUnavailable      = "PAYMENT_METHOD_UNAVAILABLE"
	CodePaymentProviderUnavailable    = "PAYMENT_PROVIDER_UNAVAILABLE"
	CodePaymentProviderNotImplemented = "PAYMENT_PROVIDER_NOT_IMPLEMENTED"
	CodePaymentAmountOutOfRange       = "PAYMENT_AMOUNT_OUT_OF_RANGE"
	CodePaymentTooManyPending         = "PAYMENT_TOO_MANY_PENDING_ORDERS"
	CodePaymentSignatureInvalid       = "PAYMENT_SIGNATURE_INVALID"
	CodePaymentAmountMismatch         = "PAYMENT_AMOUNT_MISMATCH"
	CodeLoginRequiredGalleryDetail    = "LOGIN_REQUIRED_FOR_GALLERY_DETAIL"
	CodeSignupTrialConfigInvalid      = "SIGNUP_TRIAL_CONFIG_INVALID"
)
