// Code generated by ent, DO NOT EDIT.

package promptoptimizationrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the promptoptimizationrun type in the database.
	Label = "prompt_optimization_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldModelCode holds the string denoting the model_code field in the database.
	FieldModelCode = "model_code"
	// FieldAPIStyle holds the string denoting the api_style field in the database.
	FieldAPIStyle = "api_style"
	// FieldConfigVersion holds the string denoting the config_version field in the database.
	FieldConfigVersion = "config_version"
	// FieldPromptSha256 holds the string denoting the prompt_sha256 field in the database.
	FieldPromptSha256 = "prompt_sha256"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldEstimatedPoints holds the string denoting the estimated_points field in the database.
	FieldEstimatedPoints = "estimated_points"
	// FieldActualPoints holds the string denoting the actual_points field in the database.
	FieldActualPoints = "actual_points"
	// FieldProviderRequestID holds the string denoting the provider_request_id field in the database.
	FieldProviderRequestID = "provider_request_id"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// Table holds the table name of the promptoptimizationrun in the database.
	Table = "prompt_optimization_runs"
)

// Columns holds all SQL columns for promptoptimizationrun fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldAccountID,
	FieldModelID,
	FieldModelCode,
	FieldAPIStyle,
	FieldConfigVersion,
	FieldPromptSha256,
	FieldStatus,
	FieldInputTokens,
	FieldOutputTokens,
	FieldEstimatedPoints,
	FieldActualPoints,
	FieldProviderRequestID,
	FieldErrorCode,
	FieldErrorMessage,
	FieldMetadata,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ModelCodeValidator is a validator for the "model_code" field. It is called by the builders before save.
	ModelCodeValidator func(string) error
	// APIStyleValidator is a validator for the "api_style" field. It is called by the builders before save.
	APIStyleValidator func(string) error
	// PromptSha256Validator is a validator for the "prompt_sha256" field. It is called by the builders before save.
	PromptSha256Validator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int
	// DefaultEstimatedPoints holds the default value on creation for the "estimated_points" field.
	DefaultEstimatedPoints string
	// DefaultActualPoints holds the default value on creation for the "actual_points" field.
	DefaultActualPoints string
	// DefaultProviderRequestID holds the default value on creation for the "provider_request_id" field.
	DefaultProviderRequestID string
	// ProviderRequestIDValidator is a validator for the "provider_request_id" field. It is called by the builders before save.
	ProviderRequestIDValidator func(string) error
	// DefaultErrorCode holds the default value on creation for the "error_code" field.
	DefaultErrorCode string
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultErrorMessage holds the default value on creation for the "error_message" field.
	DefaultErrorMessage string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PromptOptimizationRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByModelCode orders the results by the model_code field.
func ByModelCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelCode, opts...).ToFunc()
}

// ByAPIStyle orders the results by the api_style field.
func ByAPIStyle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIStyle, opts...).ToFunc()
}

// ByConfigVersion orders the results by the config_version field.
func ByConfigVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigVersion, opts...).ToFunc()
}

// ByPromptSha256 orders the results by the prompt_sha256 field.
func ByPromptSha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptSha256, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByEstimatedPoints orders the results by the estimated_points field.
func ByEstimatedPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedPoints, opts...).ToFunc()
}

// ByActualPoints orders the results by the actual_points field.
func ByActualPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualPoints, opts...).ToFunc()
}

// ByProviderRequestID orders the results by the provider_request_id field.
func ByProviderRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderRequestID, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}
