// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/fatballfish/pic-gallery/internal/repository/ent"
)

// The APIKeyFunc type is an adapter to allow the use of ordinary
// function as APIKey mutator.
type APIKeyFunc func(context.Context, *ent.APIKeyMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f APIKeyFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.APIKeyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.APIKeyMutation", m)
}

// The APIKeyQuotaReservationFunc type is an adapter to allow the use of ordinary
// function as APIKeyQuotaReservation mutator.
type APIKeyQuotaReservationFunc func(context.Context, *ent.APIKeyQuotaReservationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f APIKeyQuotaReservationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.APIKeyQuotaReservationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.APIKeyQuotaReservationMutation", m)
}

// The AdminUserFunc type is an adapter to allow the use of ordinary
// function as AdminUser mutator.
type AdminUserFunc func(context.Context, *ent.AdminUserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AdminUserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AdminUserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AdminUserMutation", m)
}

// The AuditLogFunc type is an adapter to allow the use of ordinary
// function as AuditLog mutator.
type AuditLogFunc func(context.Context, *ent.AuditLogMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AuditLogFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AuditLogMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AuditLogMutation", m)
}

// The ConfigItemFunc type is an adapter to allow the use of ordinary
// function as ConfigItem mutator.
type ConfigItemFunc func(context.Context, *ent.ConfigItemMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ConfigItemFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ConfigItemMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ConfigItemMutation", m)
}

// The ImageResultFunc type is an adapter to allow the use of ordinary
// function as ImageResult mutator.
type ImageResultFunc func(context.Context, *ent.ImageResultMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ImageResultFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ImageResultMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ImageResultMutation", m)
}

// The ImageTaskFunc type is an adapter to allow the use of ordinary
// function as ImageTask mutator.
type ImageTaskFunc func(context.Context, *ent.ImageTaskMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ImageTaskFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ImageTaskMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ImageTaskMutation", m)
}

// The ModelAccountFunc type is an adapter to allow the use of ordinary
// function as ModelAccount mutator.
type ModelAccountFunc func(context.Context, *ent.ModelAccountMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ModelAccountFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ModelAccountMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ModelAccountMutation", m)
}

// The ModelAccountModelFunc type is an adapter to allow the use of ordinary
// function as ModelAccountModel mutator.
type ModelAccountModelFunc func(context.Context, *ent.ModelAccountModelMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ModelAccountModelFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ModelAccountModelMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ModelAccountModelMutation", m)
}

// The ModelProviderFunc type is an adapter to allow the use of ordinary
// function as ModelProvider mutator.
type ModelProviderFunc func(context.Context, *ent.ModelProviderMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ModelProviderFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ModelProviderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ModelProviderMutation", m)
}

// The ModelRouteFunc type is an adapter to allow the use of ordinary
// function as ModelRoute mutator.
type ModelRouteFunc func(context.Context, *ent.ModelRouteMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ModelRouteFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ModelRouteMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ModelRouteMutation", m)
}

// The ObjectStorageConfigFunc type is an adapter to allow the use of ordinary
// function as ObjectStorageConfig mutator.
type ObjectStorageConfigFunc func(context.Context, *ent.ObjectStorageConfigMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ObjectStorageConfigFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ObjectStorageConfigMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ObjectStorageConfigMutation", m)
}

// The PaymentOrderFunc type is an adapter to allow the use of ordinary
// function as PaymentOrder mutator.
type PaymentOrderFunc func(context.Context, *ent.PaymentOrderMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PaymentOrderFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PaymentOrderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PaymentOrderMutation", m)
}

// The PaymentProviderInstanceFunc type is an adapter to allow the use of ordinary
// function as PaymentProviderInstance mutator.
type PaymentProviderInstanceFunc func(context.Context, *ent.PaymentProviderInstanceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PaymentProviderInstanceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PaymentProviderInstanceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PaymentProviderInstanceMutation", m)
}

// The PaymentWebhookEventFunc type is an adapter to allow the use of ordinary
// function as PaymentWebhookEvent mutator.
type PaymentWebhookEventFunc func(context.Context, *ent.PaymentWebhookEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PaymentWebhookEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PaymentWebhookEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PaymentWebhookEventMutation", m)
}

// The PointLedgerFunc type is an adapter to allow the use of ordinary
// function as PointLedger mutator.
type PointLedgerFunc func(context.Context, *ent.PointLedgerMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PointLedgerFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PointLedgerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PointLedgerMutation", m)
}

// The PromptOptimizationRunFunc type is an adapter to allow the use of ordinary
// function as PromptOptimizationRun mutator.
type PromptOptimizationRunFunc func(context.Context, *ent.PromptOptimizationRunMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PromptOptimizationRunFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PromptOptimizationRunMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PromptOptimizationRunMutation", m)
}

// The ProviderErrorPolicyFunc type is an adapter to allow the use of ordinary
// function as ProviderErrorPolicy mutator.
type ProviderErrorPolicyFunc func(context.Context, *ent.ProviderErrorPolicyMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ProviderErrorPolicyFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ProviderErrorPolicyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ProviderErrorPolicyMutation", m)
}

// The ProviderModelFunc type is an adapter to allow the use of ordinary
// function as ProviderModel mutator.
type ProviderModelFunc func(context.Context, *ent.ProviderModelMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ProviderModelFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ProviderModelMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ProviderModelMutation", m)
}

// The PublicImageInteractionFunc type is an adapter to allow the use of ordinary
// function as PublicImageInteraction mutator.
type PublicImageInteractionFunc func(context.Context, *ent.PublicImageInteractionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PublicImageInteractionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PublicImageInteractionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PublicImageInteractionMutation", m)
}

// The PublicImageStatFunc type is an adapter to allow the use of ordinary
// function as PublicImageStat mutator.
type PublicImageStatFunc func(context.Context, *ent.PublicImageStatMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PublicImageStatFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PublicImageStatMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PublicImageStatMutation", m)
}

// The RedeemCodeFunc type is an adapter to allow the use of ordinary
// function as RedeemCode mutator.
type RedeemCodeFunc func(context.Context, *ent.RedeemCodeMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RedeemCodeFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RedeemCodeMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RedeemCodeMutation", m)
}

// The ReferenceAssetFunc type is an adapter to allow the use of ordinary
// function as ReferenceAsset mutator.
type ReferenceAssetFunc func(context.Context, *ent.ReferenceAssetMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ReferenceAssetFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ReferenceAssetMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ReferenceAssetMutation", m)
}

// The RefreshSessionFunc type is an adapter to allow the use of ordinary
// function as RefreshSession mutator.
type RefreshSessionFunc func(context.Context, *ent.RefreshSessionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RefreshSessionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RefreshSessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RefreshSessionMutation", m)
}

// The RouteModelFunc type is an adapter to allow the use of ordinary
// function as RouteModel mutator.
type RouteModelFunc func(context.Context, *ent.RouteModelMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RouteModelFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RouteModelMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RouteModelMutation", m)
}

// The RouteModelCandidateFunc type is an adapter to allow the use of ordinary
// function as RouteModelCandidate mutator.
type RouteModelCandidateFunc func(context.Context, *ent.RouteModelCandidateMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RouteModelCandidateFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RouteModelCandidateMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RouteModelCandidateMutation", m)
}

// The RouteModelPriceFunc type is an adapter to allow the use of ordinary
// function as RouteModelPrice mutator.
type RouteModelPriceFunc func(context.Context, *ent.RouteModelPriceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RouteModelPriceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RouteModelPriceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RouteModelPriceMutation", m)
}

// The RouteModelVisibilityGroupFunc type is an adapter to allow the use of ordinary
// function as RouteModelVisibilityGroup mutator.
type RouteModelVisibilityGroupFunc func(context.Context, *ent.RouteModelVisibilityGroupMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RouteModelVisibilityGroupFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RouteModelVisibilityGroupMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RouteModelVisibilityGroupMutation", m)
}

// The SecureConfigFunc type is an adapter to allow the use of ordinary
// function as SecureConfig mutator.
type SecureConfigFunc func(context.Context, *ent.SecureConfigMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SecureConfigFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SecureConfigMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SecureConfigMutation", m)
}

// The SubscriptionPlanFunc type is an adapter to allow the use of ordinary
// function as SubscriptionPlan mutator.
type SubscriptionPlanFunc func(context.Context, *ent.SubscriptionPlanMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SubscriptionPlanFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SubscriptionPlanMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SubscriptionPlanMutation", m)
}

// The TextModelFunc type is an adapter to allow the use of ordinary
// function as TextModel mutator.
type TextModelFunc func(context.Context, *ent.TextModelMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TextModelFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TextModelMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TextModelMutation", m)
}

// The TextModelAccountFunc type is an adapter to allow the use of ordinary
// function as TextModelAccount mutator.
type TextModelAccountFunc func(context.Context, *ent.TextModelAccountMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TextModelAccountFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TextModelAccountMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TextModelAccountMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *ent.UserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserMutation", m)
}

// The UserGroupFunc type is an adapter to allow the use of ordinary
// function as UserGroup mutator.
type UserGroupFunc func(context.Context, *ent.UserGroupMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserGroupFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserGroupMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserGroupMutation", m)
}

// The UserGroupMemberFunc type is an adapter to allow the use of ordinary
// function as UserGroupMember mutator.
type UserGroupMemberFunc func(context.Context, *ent.UserGroupMemberMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserGroupMemberFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserGroupMemberMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserGroupMemberMutation", m)
}

// The UserSubscriptionFunc type is an adapter to allow the use of ordinary
// function as UserSubscription mutator.
type UserSubscriptionFunc func(context.Context, *ent.UserSubscriptionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserSubscriptionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserSubscriptionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserSubscriptionMutation", m)
}

// The WalletGrantFunc type is an adapter to allow the use of ordinary
// function as WalletGrant mutator.
type WalletGrantFunc func(context.Context, *ent.WalletGrantMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WalletGrantFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.WalletGrantMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WalletGrantMutation", m)
}

// The WalletReservationAllocationFunc type is an adapter to allow the use of ordinary
// function as WalletReservationAllocation mutator.
type WalletReservationAllocationFunc func(context.Context, *ent.WalletReservationAllocationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WalletReservationAllocationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.WalletReservationAllocationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WalletReservationAllocationMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
