package router

import (
	"net/http"
	stdpprof "net/http/pprof"

	"github.com/fatballfish/pic-gallery/internal/app/observability"
	"github.com/fatballfish/pic-gallery/internal/config"
	"github.com/fatballfish/pic-gallery/internal/http/handlers"
	"github.com/fatballfish/pic-gallery/internal/http/middleware"
)

func New() http.Handler {
	return newMux(nil, nil)
}

func NewWithAPI(api *handlers.API) http.Handler {
	return newMux(api, nil)
}

func NewWithAPIAndConfig(api *handlers.API, cfg config.Config) http.Handler {
	return newMux(api, cfg.HTTP.CORSAllowedOrigins)
}

func newMux(api *handlers.API, corsAllowedOrigins []string) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/", handlers.Root)
	mux.HandleFunc("/api/", handlers.APINotFound)
	mux.HandleFunc("/healthz", handlers.Healthz)
	mux.HandleFunc("/readyz", handlers.Readyz)
	mux.Handle("/metrics", handlers.Metrics())
	mux.HandleFunc("/debug/pprof/", stdpprof.Index)
	mux.HandleFunc("/debug/pprof/cmdline", stdpprof.Cmdline)
	mux.HandleFunc("/debug/pprof/profile", stdpprof.Profile)
	mux.HandleFunc("/debug/pprof/symbol", stdpprof.Symbol)
	mux.HandleFunc("/debug/pprof/trace", stdpprof.Trace)
	if api != nil {
		mux.HandleFunc("/v1/images/generations", api.HandleOpenAIImageGeneration)
		mux.HandleFunc("/v1/images/edits", api.HandleOpenAIImageEdit)
		mux.HandleFunc("/v1/models", api.HandleOpenAIModels)
		mux.HandleFunc("/api/agent/auth/v1/email/send-code", api.HandleSendEmailCode)
		mux.HandleFunc("/api/agent/auth/v1/login/email-code", api.HandleEmailCodeLogin)
		mux.HandleFunc("/api/agent/auth/v1/login/password", api.HandlePasswordLogin)
		mux.HandleFunc("/api/agent/auth/v1/session/refresh", api.HandleRefresh)
		mux.HandleFunc("/api/agent/auth/v1/logout", api.HandleLogout)
		mux.HandleFunc("/api/agent/auth/v1/password/change", api.HandleChangePassword)
		mux.HandleFunc("/api/agent/auth/v1/password/reset", api.HandleResetPassword)
		mux.HandleFunc("/api/agent/auth/v1/password/reset/request", api.HandlePasswordResetRequest)
		mux.HandleFunc("/api/agent/auth/v1/password/reset/confirm", api.HandlePasswordResetConfirm)
		mux.HandleFunc("/api/agent/user/v1/profile", api.HandleProfile)
		mux.HandleFunc("/api/agent/user/v1/preferences", api.HandlePreferences)
		mux.HandleFunc("/api/agent/user/v1/avatar", api.HandleAvatar)
		mux.HandleFunc("/api/agent/user/v1/account/close", api.HandleCloseAccount)
		mux.HandleFunc("/api/agent/gallery/v1/images", api.HandleAgentGalleryImages)
		mux.HandleFunc("/api/agent/gallery/v1/images/", api.HandleAgentGalleryImageDetail)
		mux.HandleFunc("/api/agent/billing/v1/balance", api.HandleBalance)
		mux.HandleFunc("/api/agent/billing/v1/ledger", api.HandleLedger)
		mux.HandleFunc("/api/agent/billing/v1/plans", api.HandleBillingPlans)
		mux.HandleFunc("/api/agent/billing/v1/subscription", api.HandleBillingSubscription)
		mux.HandleFunc("/api/agent/billing/v1/orders", api.HandleBillingOrders)
		mux.HandleFunc("/api/agent/billing/v1/orders/", api.HandleBillingOrderDetail)
		mux.HandleFunc("/api/agent/cashier/v1/options", api.HandleCashierOptions)
		mux.HandleFunc("/api/agent/cashier/v1/orders", api.HandleCashierOrders)
		mux.HandleFunc("/api/agent/cashier/v1/orders/", api.HandleCashierOrderDetail)
		mux.HandleFunc("/api/agent/image/v1/capabilities", api.HandleCapabilities)
		mux.HandleFunc("/api/agent/billing/v1/estimate", api.HandleEstimate)
		mux.HandleFunc("/api/agent/account/v1/api-keys", api.HandleAgentAPIKeys)
		mux.HandleFunc("/api/agent/account/v1/api-keys/", api.HandleAgentAPIKeyDetail)
		mux.HandleFunc("/api/agent/developer/v1/api-keys", api.HandleDeveloperAPIKeys)
		mux.HandleFunc("/api/agent/developer/v1/api-keys/", api.HandleDeveloperAPIKeyDetail)
		mux.HandleFunc("/api/agent/billing/v1/redeem-codes/redeem", api.HandleRedeemCode)
		mux.HandleFunc("/api/agent/image/v1/reference-assets", api.HandleReferenceAssetUpload)
		mux.HandleFunc("/api/agent/image/v1/reference-assets:import-from-gallery", api.HandleReferenceAssetsImportFromGallery)
		mux.HandleFunc("/api/agent/image/v1/reference-assets/", api.HandleReferenceAssetGet)
		mux.HandleFunc("/api/agent/image/v1/images/", api.HandleImageDownload)
		mux.HandleFunc("/api/agent/image/v1/tasks", api.HandleAgentTasks)
		mux.HandleFunc("/api/agent/image/v1/tasks/events", api.HandleAgentTaskEvents)
		mux.HandleFunc("/api/agent/image/v1/tasks/", api.HandleAgentTaskDetail)
		mux.HandleFunc("/api/agent/image/v1/history/tasks", api.HandleAgentHistoryTasks)
		mux.HandleFunc("/api/agent/image/v1/history/tasks/", api.HandleAgentHistoryTaskDetail)
		mux.HandleFunc("/api/open/image/v1/reference-assets/uploads", api.HandleOpenReferenceAssetUploadSession)
		mux.HandleFunc("/api/open/image/v1/reference-assets", api.HandleOpenReferenceAssetMultipartUpload)
		mux.HandleFunc("/api/open/image/v1/reference-assets/", api.HandleOpenReferenceAssetGet)
		mux.HandleFunc("/api/open/image/v1/tasks", api.HandleOpenTasks)
		mux.HandleFunc("/api/open/image/v1/tasks/", api.HandleOpenTaskDetail)
		mux.HandleFunc("/api/open/image/v1/balance", api.HandleOpenBalance)
		mux.HandleFunc("/api/open/image/v1/capabilities", api.HandleOpenCapabilities)
		mux.HandleFunc("/api/open/image/v1/estimate", api.HandleOpenEstimate)
		mux.HandleFunc("/api/open/image/v1/gallery/images", api.HandleOpenGalleryImages)
		mux.HandleFunc("/api/open/image/v1/gallery/images/", api.HandleOpenGalleryImageDetail)
		mux.HandleFunc("/api/open/image/v1/payments/webhooks/", api.HandlePaymentWebhook)
		mux.HandleFunc("/api/ops/admin/v1/auth/login", api.HandleAdminLogin)
		mux.HandleFunc("/api/ops/admin/v1/auth/session/refresh", api.HandleAdminRefresh)
		mux.HandleFunc("/api/ops/admin/v1/auth/logout", api.HandleAdminLogout)
		mux.HandleFunc("/api/ops/admin/v1/audit-logs", api.HandleAdminAuditLogs)
		mux.HandleFunc("/api/ops/admin/v1/image-reviews", api.HandleAdminImageReviews)
		mux.HandleFunc("/api/ops/admin/v1/image-reviews/", api.HandleAdminImageReviewDetail)
		mux.HandleFunc("/api/ops/admin/v1/admin-users", api.HandleAdminSystemUsers)
		mux.HandleFunc("/api/ops/admin/v1/admin-users/", api.HandleAdminSystemUserDetail)
		mux.HandleFunc("/api/ops/admin/v1/users", api.HandleAdminUsers)
		mux.HandleFunc("/api/ops/admin/v1/users/", api.HandleAdminUserDetail)
		mux.HandleFunc("/api/ops/admin/v1/user-groups", api.HandleAdminUserGroups)
		mux.HandleFunc("/api/ops/admin/v1/user-groups/", api.HandleAdminUserGroupDetail)
		mux.HandleFunc("/api/ops/admin/v1/redeem-codes:batch-create", api.HandleAdminRedeemCodeBatchCreate)
		mux.HandleFunc("/api/ops/admin/v1/redeem-codes:export", api.HandleAdminRedeemCodeExport)
		mux.HandleFunc("/api/ops/admin/v1/redeem-codes", api.HandleAdminRedeemCodes)
		mux.HandleFunc("/api/ops/admin/v1/redeem-codes/", api.HandleAdminRedeemCodeDetail)
		mux.HandleFunc("/api/ops/admin/v1/call-records", api.HandleAdminCallRecords)
		mux.HandleFunc("/api/ops/admin/v1/model-accounts", api.HandleAdminModelAccounts)
		mux.HandleFunc("/api/ops/admin/v1/model-accounts/", api.HandleAdminModelAccountDetail)
		mux.HandleFunc("/api/ops/admin/v1/route-models", api.HandleAdminRouteModels)
		mux.HandleFunc("/api/ops/admin/v1/route-models/", api.HandleAdminRouteModelDetail)
		mux.HandleFunc("/api/ops/admin/v1/route-model-prices", api.HandleAdminRouteModelPrices)
		mux.HandleFunc("/api/ops/admin/v1/route-model-prices/", api.HandleAdminRouteModelPriceDetail)
		mux.HandleFunc("/api/ops/admin/v1/model-providers", api.HandleAdminModelProviders)
		mux.HandleFunc("/api/ops/admin/v1/model-providers/", api.HandleAdminModelProviderDetail)
		mux.HandleFunc("/api/ops/admin/v1/provider-models", api.HandleAdminProviderModels)
		mux.HandleFunc("/api/ops/admin/v1/provider-models/", api.HandleAdminProviderModelDetail)
		mux.HandleFunc("/api/ops/admin/v1/model-routes", api.HandleAdminModelRoutes)
		mux.HandleFunc("/api/ops/admin/v1/model-routes/", api.HandleAdminModelRouteDetail)
		mux.HandleFunc("/api/ops/admin/v1/metrics/dashboard", api.HandleAdminDashboard)
		mux.HandleFunc("/api/ops/admin/v1/readiness", api.HandleAdminReadiness)
		mux.HandleFunc("/api/ops/admin/v1/cashier/overview", api.HandleAdminCashierOverview)
		mux.HandleFunc("/api/ops/admin/v1/cashier/plans", api.HandleAdminCashierPlans)
		mux.HandleFunc("/api/ops/admin/v1/cashier/plans/", api.HandleAdminCashierPlanDetail)
		mux.HandleFunc("/api/ops/admin/v1/cashier/custom-amount-config", api.HandleAdminCashierCustomAmountConfig)
		mux.HandleFunc("/api/ops/admin/v1/cashier/visible-methods", api.HandleAdminCashierVisibleMethods)
		mux.HandleFunc("/api/ops/admin/v1/cashier/visible-methods/", api.HandleAdminCashierVisibleMethods)
		mux.HandleFunc("/api/ops/admin/v1/cashier/provider-instances", api.HandleAdminCashierProviderInstances)
		mux.HandleFunc("/api/ops/admin/v1/cashier/provider-instances/", api.HandleAdminCashierProviderInstanceDetail)
		mux.HandleFunc("/api/ops/admin/v1/cashier/orders", api.HandleAdminCashierOrders)
		mux.HandleFunc("/api/ops/admin/v1/cashier/orders/", api.HandleAdminCashierOrderDetail)
		mux.HandleFunc("/api/ops/admin/v1/cashier/webhook-events", api.HandleAdminCashierWebhookEvents)
		mux.HandleFunc("/api/ops/admin/v1/cashier/webhook-events/", api.HandleAdminCashierWebhookEventDetail)
		mux.HandleFunc("/api/ops/admin/v1/config-tabs", api.HandleAdminConfigTabs)
		mux.HandleFunc("/api/ops/admin/v1/config-tabs/", api.HandleAdminConfigTabDetail)
		mux.HandleFunc("/api/ops/admin/v1/storage-configs", api.HandleAdminStorageConfigs)
		mux.HandleFunc("/api/ops/admin/v1/storage-configs:probe", api.HandleAdminStorageConfigProbe)
		mux.HandleFunc("/api/ops/admin/v1/storage-configs/", api.HandleAdminStorageConfigDetail)
		mux.HandleFunc("/api/ops/admin/v1/security/smtp", api.HandleAdminSecuritySMTP)
		mux.HandleFunc("/api/ops/admin/v1/security/smtp/test", api.HandleAdminSecuritySMTPTest)
		mux.HandleFunc("/docs/openapi.yaml", api.HandleDocsOpenAPIYAML)
		mux.HandleFunc("/docs/openapi.json", api.HandleDocsOpenAPIJSON)
		mux.HandleFunc("/docs/examples", api.HandleDocsExamples)
		mux.HandleFunc("/docs/errors", api.HandleDocsErrors)
	}

	handler := middleware.Recovery(mux)
	handler = middleware.RequestID(handler)
	handler = middleware.Metrics(handler)
	handler = middleware.CORSWithAllowedOrigins(corsAllowedOrigins, handler)
	handler = observability.RequestLogger(handler)
	return handler
}
