export const adminShell = {
  root: 'flex h-screen overflow-hidden bg-[var(--bg)] text-[var(--text)] selection:bg-[var(--accent)]/30 max-[920px]:h-auto max-[920px]:min-h-screen max-[920px]:flex-col',
  sidebar: 'z-20 flex w-72 shrink-0 flex-col border-r border-[var(--line)] bg-[var(--shell)] transition-all duration-500 ease-[cubic-bezier(0.32,0.72,0,1)] max-[920px]:w-full max-[920px]:border-r-0 max-[920px]:border-b',
  brand: 'flex h-20 items-center gap-3 border-b border-[var(--line)] px-8 text-[var(--text)] no-underline max-[920px]:h-auto max-[920px]:px-4 max-[920px]:py-3',
  brandOrb: 'grid size-8 place-items-center rounded-lg bg-gradient-to-br from-[var(--accent)] to-[var(--accent-purple)] text-sm font-black text-white',
  brandText: 'text-lg font-bold tracking-tight text-[var(--text)]',
  nav: 'flex-1 space-y-8 overflow-y-auto px-4 py-6 max-[920px]:flex max-[920px]:gap-3 max-[920px]:space-y-0 max-[920px]:overflow-x-auto max-[920px]:py-3',
  navGroup: 'space-y-1 max-[920px]:min-w-max',
  navLabel: 'mb-2 px-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[var(--muted-strong)]',
  navLink: 'group flex w-fit max-w-full items-center gap-3 rounded-xl border border-transparent px-4 py-2.5 text-sm font-medium text-[var(--muted)] no-underline transition-all hover:bg-white/5 hover:text-[var(--text)]',
  navLinkActive: 'admin-nav-active bg-transparent text-[var(--text)] hover:bg-transparent hover:text-[var(--text)]',
  navIcon: 'grid size-5 place-items-center',
  navBadge: 'ml-auto rounded-full bg-white/10 px-2 py-0.5 text-[10px] font-bold not-italic text-[var(--muted)]',
  sideNote: 'm-6 mt-auto flex min-w-0 items-center gap-3 border-t border-[var(--line)] pt-6 max-[920px]:hidden',
  main: 'flex min-w-0 flex-1 flex-col overflow-hidden',
  topbar: 'flex h-20 shrink-0 items-center justify-between gap-4 border-b border-[var(--line)] bg-[var(--topbar)] px-10 backdrop-blur-xl max-[920px]:h-auto max-[920px]:px-4 max-[920px]:py-3 max-[720px]:flex-col max-[720px]:items-start',
  titleBlock: 'flex min-w-0 items-center gap-4 max-[720px]:flex-col max-[720px]:items-start max-[720px]:gap-1',
  pageTitle: 'text-xl font-bold tracking-tight text-[var(--text)]',
  breadcrumb: 'flex items-center gap-2 border-l border-[var(--line)] pl-4 text-[10px] font-bold uppercase tracking-widest text-[var(--muted-strong)] max-[720px]:border-l-0 max-[720px]:pl-0 [&_strong]:text-[var(--accent)]',
  flexRow: 'flex flex-wrap items-center gap-2',
  metaRow: 'flex flex-wrap items-center justify-end gap-2',
  chip: 'inline-flex min-h-[34px] items-center gap-2 rounded-full border border-[var(--line)] bg-white/5 px-2.5 py-[7px] text-[var(--muted)]',
  providerPill: 'inline-flex items-center gap-2 rounded-lg border border-[var(--line)] bg-white/5 px-3 py-2 text-[var(--muted)] uppercase tracking-wider',
  iconButton: 'grid size-10 place-items-center rounded-xl border border-[var(--line)] bg-white/5 text-[var(--muted)] transition-colors hover:text-[var(--text)]',
  avatarWidget: 'flex items-center gap-2.5',
  avatarOrb: 'grid size-10 place-items-center rounded-xl bg-white/5 text-sm font-bold text-[var(--muted)]',
  statusStrip: 'grid shrink-0 grid-cols-5 border-b border-[var(--line)] bg-[#0a0a0a]/30 max-[1260px]:grid-cols-3 max-[920px]:grid-cols-2 max-[620px]:grid-cols-1',
  statusCell: 'min-w-0 border-r border-[var(--line)] px-4 py-3 last:border-r-0 max-[920px]:even:border-r-0 max-[620px]:border-r-0 max-[620px]:border-b max-[620px]:last:border-b-0',
  statusLabel: 'block text-[10px] font-extrabold uppercase tracking-[.14em] text-[var(--muted-strong)]',
  statusValue: 'mt-1 block truncate text-[var(--text)]',
  content: 'flex-1 overflow-y-auto bg-[radial-gradient(circle_at_50%_0%,color-mix(in_oklch,var(--accent)_8%,transparent),transparent_46%)] p-10 max-[920px]:p-4',
}

export const adminButton = {
  base: 'inline-flex min-h-9 items-center justify-center gap-2 rounded-xl border border-[var(--line)] px-3 py-2 text-sm font-bold transition hover:-translate-y-px disabled:pointer-events-none disabled:opacity-50',
  primary: 'border-[var(--accent)] bg-[var(--accent)] text-white shadow-lg shadow-[var(--accent)]/20',
  ghost: 'bg-white/5 text-[var(--text)] hover:border-white/10 hover:bg-white/10',
  danger: 'border-rose-500/20 bg-rose-500/10 text-rose-400',
  success: 'border-emerald-500/20 bg-emerald-500/10 text-emerald-400',
  small: 'min-h-8 px-2.5 py-1.5 text-xs',
}

export const adminSurface = {
  card: 'rounded-3xl border border-[var(--line)] bg-white/[0.02] shadow-[var(--pg-shadow-sm)] backdrop-blur-sm',
  lane: 'min-w-0 rounded-3xl border border-[var(--line)] bg-white/[0.01]',
}

export const adminPage = {
  stack: 'grid min-h-0 gap-6',
  scrollStack: 'grid min-h-0 gap-6',
  fullSurface: 'grid min-h-0 grid-cols-1 overflow-hidden rounded-3xl border border-[var(--line)] bg-white/[0.01]',
  splitSurface: 'grid min-h-0 grid-cols-[minmax(0,1fr)_280px] gap-3 overflow-hidden rounded-3xl border border-[var(--line)] bg-white/[0.01] max-[1260px]:grid-cols-1',
  formGrid: 'grid grid-cols-2 gap-3 max-[620px]:grid-cols-1',
  filterBand: 'rounded-3xl border border-[var(--line)] bg-white/[0.02] p-4 shadow-[var(--pg-shadow-sm)] backdrop-blur-sm',
  filterRow: 'flex flex-wrap items-center gap-2',
  mainLane: 'min-w-0 overflow-auto p-4',
  sideRail: 'grid min-w-0 content-start overflow-y-auto border-l border-[var(--line)] bg-white/[0.02] max-[1260px]:border-l-0 max-[1260px]:border-t',
  signalSection: 'grid gap-2 border-b border-[var(--line)] p-4 last:border-b-0',
  toolbar: 'mb-3 flex flex-wrap items-center justify-between gap-3',
  pagination: 'mt-3 flex flex-wrap items-center justify-between gap-3',
  microTabs: 'mb-3 flex flex-wrap items-center gap-2',
  microTab: 'min-h-8 rounded-full border border-[var(--line)] bg-white/5 px-3 py-1.5 text-xs font-extrabold uppercase tracking-[.08em] text-[var(--muted)] hover:border-white/10 hover:bg-white/10',
  microTabActive: 'border-[var(--accent)]/25 bg-[var(--accent)]/10 text-[var(--accent)]',
  mutedAction: 'text-xs font-extrabold text-[var(--soft)]',
  detailStack: 'grid gap-3',
  detailSection: 'grid min-w-0 gap-3',
  sectionHead: 'flex flex-wrap items-center justify-between gap-2 border-b border-[var(--line)] pb-3',
  sectionTitle: 'font-bold text-[var(--text)]',
}
