FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/pic-gallery-worker ./cmd/worker

FROM alpine:3.20
WORKDIR /app
COPY --from=build /out/pic-gallery-worker /usr/local/bin/pic-gallery-worker
COPY configs ./configs
ENTRYPOINT ["pic-gallery-worker"]
