// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/apikeyquotareservation"
)

// APIKeyQuotaReservation is the model entity for the APIKeyQuotaReservation schema.
type APIKeyQuotaReservation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// ReservationID holds the value of the "reservation_id" field.
	ReservationID string `json:"reservation_id,omitempty"`
	// Points holds the value of the "points" field.
	Points string `json:"points,omitempty"`
	// UsageDay holds the value of the "usage_day" field.
	UsageDay string `json:"usage_day,omitempty"`
	// Status holds the value of the "status" field.
	Status       string `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*APIKeyQuotaReservation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apikeyquotareservation.FieldID, apikeyquotareservation.FieldAPIKeyID:
			values[i] = new(sql.NullInt64)
		case apikeyquotareservation.FieldReservationID, apikeyquotareservation.FieldPoints, apikeyquotareservation.FieldUsageDay, apikeyquotareservation.FieldStatus:
			values[i] = new(sql.NullString)
		case apikeyquotareservation.FieldCreatedAt, apikeyquotareservation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the APIKeyQuotaReservation fields.
func (_m *APIKeyQuotaReservation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apikeyquotareservation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case apikeyquotareservation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case apikeyquotareservation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case apikeyquotareservation.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case apikeyquotareservation.FieldReservationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reservation_id", values[i])
			} else if value.Valid {
				_m.ReservationID = value.String
			}
		case apikeyquotareservation.FieldPoints:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field points", values[i])
			} else if value.Valid {
				_m.Points = value.String
			}
		case apikeyquotareservation.FieldUsageDay:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usage_day", values[i])
			} else if value.Valid {
				_m.UsageDay = value.String
			}
		case apikeyquotareservation.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the APIKeyQuotaReservation.
// This includes values selected through modifiers, order, etc.
func (_m *APIKeyQuotaReservation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this APIKeyQuotaReservation.
// Note that you need to call APIKeyQuotaReservation.Unwrap() before calling this method if this APIKeyQuotaReservation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *APIKeyQuotaReservation) Update() *APIKeyQuotaReservationUpdateOne {
	return NewAPIKeyQuotaReservationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the APIKeyQuotaReservation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *APIKeyQuotaReservation) Unwrap() *APIKeyQuotaReservation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: APIKeyQuotaReservation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *APIKeyQuotaReservation) String() string {
	var builder strings.Builder
	builder.WriteString("APIKeyQuotaReservation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("reservation_id=")
	builder.WriteString(_m.ReservationID)
	builder.WriteString(", ")
	builder.WriteString("points=")
	builder.WriteString(_m.Points)
	builder.WriteString(", ")
	builder.WriteString("usage_day=")
	builder.WriteString(_m.UsageDay)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// APIKeyQuotaReservations is a parsable slice of APIKeyQuotaReservation.
type APIKeyQuotaReservations []*APIKeyQuotaReservation
