// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/canvasgenerationrun"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/creativecanvas"
	"github.com/google/uuid"
)

// CanvasGenerationRun is the model entity for the CanvasGenerationRun schema.
type CanvasGenerationRun struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CanvasID holds the value of the "canvas_id" field.
	CanvasID uuid.UUID `json:"canvas_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// NodeID holds the value of the "node_id" field.
	NodeID string `json:"node_id,omitempty"`
	// SubmittedRevision holds the value of the "submitted_revision" field.
	SubmittedRevision int64 `json:"submitted_revision,omitempty"`
	// TaskKind holds the value of the "task_kind" field.
	TaskKind string `json:"task_kind,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID uuid.UUID `json:"task_id,omitempty"`
	// NodeSnapshot holds the value of the "node_snapshot" field.
	NodeSnapshot map[string]interface{} `json:"node_snapshot,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ResultAssetIds holds the value of the "result_asset_ids" field.
	ResultAssetIds []uuid.UUID `json:"result_asset_ids,omitempty"`
	// AttachedRevision holds the value of the "attached_revision" field.
	AttachedRevision *int64 `json:"attached_revision,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CanvasGenerationRunQuery when eager-loading is set.
	Edges        CanvasGenerationRunEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CanvasGenerationRunEdges holds the relations/edges for other nodes in the graph.
type CanvasGenerationRunEdges struct {
	// Canvas holds the value of the canvas edge.
	Canvas *CreativeCanvas `json:"canvas,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CanvasOrErr returns the Canvas value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CanvasGenerationRunEdges) CanvasOrErr() (*CreativeCanvas, error) {
	if e.Canvas != nil {
		return e.Canvas, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: creativecanvas.Label}
	}
	return nil, &NotLoadedError{edge: "canvas"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CanvasGenerationRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case canvasgenerationrun.FieldNodeSnapshot, canvasgenerationrun.FieldResultAssetIds:
			values[i] = new([]byte)
		case canvasgenerationrun.FieldUserID, canvasgenerationrun.FieldSubmittedRevision, canvasgenerationrun.FieldAttachedRevision:
			values[i] = new(sql.NullInt64)
		case canvasgenerationrun.FieldNodeID, canvasgenerationrun.FieldTaskKind, canvasgenerationrun.FieldStatus, canvasgenerationrun.FieldIdempotencyKey, canvasgenerationrun.FieldErrorCode, canvasgenerationrun.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case canvasgenerationrun.FieldCreatedAt, canvasgenerationrun.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case canvasgenerationrun.FieldID, canvasgenerationrun.FieldCanvasID, canvasgenerationrun.FieldTaskID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CanvasGenerationRun fields.
func (_m *CanvasGenerationRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case canvasgenerationrun.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case canvasgenerationrun.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case canvasgenerationrun.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case canvasgenerationrun.FieldCanvasID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field canvas_id", values[i])
			} else if value != nil {
				_m.CanvasID = *value
			}
		case canvasgenerationrun.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case canvasgenerationrun.FieldNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = value.String
			}
		case canvasgenerationrun.FieldSubmittedRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_revision", values[i])
			} else if value.Valid {
				_m.SubmittedRevision = value.Int64
			}
		case canvasgenerationrun.FieldTaskKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_kind", values[i])
			} else if value.Valid {
				_m.TaskKind = value.String
			}
		case canvasgenerationrun.FieldTaskID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value != nil {
				_m.TaskID = *value
			}
		case canvasgenerationrun.FieldNodeSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field node_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NodeSnapshot); err != nil {
					return fmt.Errorf("unmarshal field node_snapshot: %w", err)
				}
			}
		case canvasgenerationrun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case canvasgenerationrun.FieldResultAssetIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field result_asset_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResultAssetIds); err != nil {
					return fmt.Errorf("unmarshal field result_asset_ids: %w", err)
				}
			}
		case canvasgenerationrun.FieldAttachedRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attached_revision", values[i])
			} else if value.Valid {
				_m.AttachedRevision = new(int64)
				*_m.AttachedRevision = value.Int64
			}
		case canvasgenerationrun.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case canvasgenerationrun.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case canvasgenerationrun.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CanvasGenerationRun.
// This includes values selected through modifiers, order, etc.
func (_m *CanvasGenerationRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCanvas queries the "canvas" edge of the CanvasGenerationRun entity.
func (_m *CanvasGenerationRun) QueryCanvas() *CreativeCanvasQuery {
	return NewCanvasGenerationRunClient(_m.config).QueryCanvas(_m)
}

// Update returns a builder for updating this CanvasGenerationRun.
// Note that you need to call CanvasGenerationRun.Unwrap() before calling this method if this CanvasGenerationRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CanvasGenerationRun) Update() *CanvasGenerationRunUpdateOne {
	return NewCanvasGenerationRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CanvasGenerationRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CanvasGenerationRun) Unwrap() *CanvasGenerationRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CanvasGenerationRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CanvasGenerationRun) String() string {
	var builder strings.Builder
	builder.WriteString("CanvasGenerationRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("canvas_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CanvasID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("node_id=")
	builder.WriteString(_m.NodeID)
	builder.WriteString(", ")
	builder.WriteString("submitted_revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubmittedRevision))
	builder.WriteString(", ")
	builder.WriteString("task_kind=")
	builder.WriteString(_m.TaskKind)
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("node_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeSnapshot))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("result_asset_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResultAssetIds))
	builder.WriteString(", ")
	if v := _m.AttachedRevision; v != nil {
		builder.WriteString("attached_revision=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// CanvasGenerationRuns is a parsable slice of CanvasGenerationRun.
type CanvasGenerationRuns []*CanvasGenerationRun
