// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/clusterchallenge"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/predicate"
)

// ClusterChallengeDelete is the builder for deleting a ClusterChallenge entity.
type ClusterChallengeDelete struct {
	config
	hooks    []Hook
	mutation *ClusterChallengeMutation
}

// Where appends a list predicates to the ClusterChallengeDelete builder.
func (_d *ClusterChallengeDelete) Where(ps ...predicate.ClusterChallenge) *ClusterChallengeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ClusterChallengeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClusterChallengeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ClusterChallengeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(clusterchallenge.Table, sqlgraph.NewFieldSpec(clusterchallenge.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ClusterChallengeDeleteOne is the builder for deleting a single ClusterChallenge entity.
type ClusterChallengeDeleteOne struct {
	_d *ClusterChallengeDelete
}

// Where appends a list predicates to the ClusterChallengeDelete builder.
func (_d *ClusterChallengeDeleteOne) Where(ps ...predicate.ClusterChallenge) *ClusterChallengeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ClusterChallengeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{clusterchallenge.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClusterChallengeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
