// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/imageresult"
	"github.com/google/uuid"
)

// ImageResult is the model entity for the ImageResult schema.
type ImageResult struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID uuid.UUID `json:"task_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ImageRole holds the value of the "image_role" field.
	ImageRole string `json:"image_role,omitempty"`
	// StorageConfigID holds the value of the "storage_config_id" field.
	StorageConfigID *int64 `json:"storage_config_id,omitempty"`
	// StorageDriver holds the value of the "storage_driver" field.
	StorageDriver string `json:"storage_driver,omitempty"`
	// ObjectKey holds the value of the "object_key" field.
	ObjectKey string `json:"object_key,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// FileSizeBytes holds the value of the "file_size_bytes" field.
	FileSizeBytes int64 `json:"file_size_bytes,omitempty"`
	// Width holds the value of the "width" field.
	Width int `json:"width,omitempty"`
	// Height holds the value of the "height" field.
	Height int `json:"height,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 string `json:"sha256,omitempty"`
	// ImageGroup holds the value of the "image_group" field.
	ImageGroup string `json:"image_group,omitempty"`
	// VisibilityStatus holds the value of the "visibility_status" field.
	VisibilityStatus string `json:"visibility_status,omitempty"`
	// ReviewReason holds the value of the "review_reason" field.
	ReviewReason *string `json:"review_reason,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt  *time.Time `json:"published_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageResult) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imageresult.FieldUserID, imageresult.FieldStorageConfigID, imageresult.FieldFileSizeBytes, imageresult.FieldWidth, imageresult.FieldHeight:
			values[i] = new(sql.NullInt64)
		case imageresult.FieldImageRole, imageresult.FieldStorageDriver, imageresult.FieldObjectKey, imageresult.FieldMimeType, imageresult.FieldSha256, imageresult.FieldImageGroup, imageresult.FieldVisibilityStatus, imageresult.FieldReviewReason:
			values[i] = new(sql.NullString)
		case imageresult.FieldCreatedAt, imageresult.FieldUpdatedAt, imageresult.FieldDeletedAt, imageresult.FieldPublishedAt:
			values[i] = new(sql.NullTime)
		case imageresult.FieldID, imageresult.FieldTaskID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageResult fields.
func (_m *ImageResult) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imageresult.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case imageresult.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imageresult.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case imageresult.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case imageresult.FieldTaskID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value != nil {
				_m.TaskID = *value
			}
		case imageresult.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case imageresult.FieldImageRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_role", values[i])
			} else if value.Valid {
				_m.ImageRole = value.String
			}
		case imageresult.FieldStorageConfigID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field storage_config_id", values[i])
			} else if value.Valid {
				_m.StorageConfigID = new(int64)
				*_m.StorageConfigID = value.Int64
			}
		case imageresult.FieldStorageDriver:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_driver", values[i])
			} else if value.Valid {
				_m.StorageDriver = value.String
			}
		case imageresult.FieldObjectKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field object_key", values[i])
			} else if value.Valid {
				_m.ObjectKey = value.String
			}
		case imageresult.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case imageresult.FieldFileSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size_bytes", values[i])
			} else if value.Valid {
				_m.FileSizeBytes = value.Int64
			}
		case imageresult.FieldWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = int(value.Int64)
			}
		case imageresult.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = int(value.Int64)
			}
		case imageresult.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case imageresult.FieldImageGroup:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_group", values[i])
			} else if value.Valid {
				_m.ImageGroup = value.String
			}
		case imageresult.FieldVisibilityStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visibility_status", values[i])
			} else if value.Valid {
				_m.VisibilityStatus = value.String
			}
		case imageresult.FieldReviewReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_reason", values[i])
			} else if value.Valid {
				_m.ReviewReason = new(string)
				*_m.ReviewReason = value.String
			}
		case imageresult.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageResult.
// This includes values selected through modifiers, order, etc.
func (_m *ImageResult) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ImageResult.
// Note that you need to call ImageResult.Unwrap() before calling this method if this ImageResult
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImageResult) Update() *ImageResultUpdateOne {
	return NewImageResultClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImageResult entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImageResult) Unwrap() *ImageResult {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageResult is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImageResult) String() string {
	var builder strings.Builder
	builder.WriteString("ImageResult(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("image_role=")
	builder.WriteString(_m.ImageRole)
	builder.WriteString(", ")
	if v := _m.StorageConfigID; v != nil {
		builder.WriteString("storage_config_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("storage_driver=")
	builder.WriteString(_m.StorageDriver)
	builder.WriteString(", ")
	builder.WriteString("object_key=")
	builder.WriteString(_m.ObjectKey)
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("file_size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSizeBytes))
	builder.WriteString(", ")
	builder.WriteString("width=")
	builder.WriteString(fmt.Sprintf("%v", _m.Width))
	builder.WriteString(", ")
	builder.WriteString("height=")
	builder.WriteString(fmt.Sprintf("%v", _m.Height))
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	builder.WriteString("image_group=")
	builder.WriteString(_m.ImageGroup)
	builder.WriteString(", ")
	builder.WriteString("visibility_status=")
	builder.WriteString(_m.VisibilityStatus)
	builder.WriteString(", ")
	if v := _m.ReviewReason; v != nil {
		builder.WriteString("review_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ImageResults is a parsable slice of ImageResult.
type ImageResults []*ImageResult
