// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/objectdeletionjob"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/predicate"
)

// ObjectDeletionJobDelete is the builder for deleting a ObjectDeletionJob entity.
type ObjectDeletionJobDelete struct {
	config
	hooks    []Hook
	mutation *ObjectDeletionJobMutation
}

// Where appends a list predicates to the ObjectDeletionJobDelete builder.
func (_d *ObjectDeletionJobDelete) Where(ps ...predicate.ObjectDeletionJob) *ObjectDeletionJobDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ObjectDeletionJobDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ObjectDeletionJobDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ObjectDeletionJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(objectdeletionjob.Table, sqlgraph.NewFieldSpec(objectdeletionjob.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ObjectDeletionJobDeleteOne is the builder for deleting a single ObjectDeletionJob entity.
type ObjectDeletionJobDeleteOne struct {
	_d *ObjectDeletionJobDelete
}

// Where appends a list predicates to the ObjectDeletionJobDelete builder.
func (_d *ObjectDeletionJobDeleteOne) Where(ps ...predicate.ObjectDeletionJob) *ObjectDeletionJobDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ObjectDeletionJobDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{objectdeletionjob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ObjectDeletionJobDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
