// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/objectstorageconfig"
	"github.com/google/uuid"
)

// ObjectStorageConfigCreate is the builder for creating a ObjectStorageConfig entity.
type ObjectStorageConfigCreate struct {
	config
	mutation *ObjectStorageConfigMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ObjectStorageConfigCreate) SetCreatedAt(v time.Time) *ObjectStorageConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableCreatedAt(v *time.Time) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ObjectStorageConfigCreate) SetUpdatedAt(v time.Time) *ObjectStorageConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableUpdatedAt(v *time.Time) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ObjectStorageConfigCreate) SetDeletedAt(v time.Time) *ObjectStorageConfigCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableDeletedAt(v *time.Time) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *ObjectStorageConfigCreate) SetCode(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ObjectStorageConfigCreate) SetName(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDriver sets the "driver" field.
func (_c *ObjectStorageConfigCreate) SetDriver(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetDriver(v)
	return _c
}

// SetNillableDriver sets the "driver" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableDriver(v *string) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetDriver(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ObjectStorageConfigCreate) SetProvider(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableProvider(v *string) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ObjectStorageConfigCreate) SetStatus(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableStatus(v *string) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReadEnabled sets the "read_enabled" field.
func (_c *ObjectStorageConfigCreate) SetReadEnabled(v bool) *ObjectStorageConfigCreate {
	_c.mutation.SetReadEnabled(v)
	return _c
}

// SetNillableReadEnabled sets the "read_enabled" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableReadEnabled(v *bool) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetReadEnabled(*v)
	}
	return _c
}

// SetWriteEnabled sets the "write_enabled" field.
func (_c *ObjectStorageConfigCreate) SetWriteEnabled(v bool) *ObjectStorageConfigCreate {
	_c.mutation.SetWriteEnabled(v)
	return _c
}

// SetNillableWriteEnabled sets the "write_enabled" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableWriteEnabled(v *bool) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetWriteEnabled(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *ObjectStorageConfigCreate) SetIsDefault(v bool) *ObjectStorageConfigCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableIsDefault(v *bool) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *ObjectStorageConfigCreate) SetEndpoint(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableEndpoint(v *string) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetEndpoint(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *ObjectStorageConfigCreate) SetRegion(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableRegion(v *string) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetBucket sets the "bucket" field.
func (_c *ObjectStorageConfigCreate) SetBucket(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetBucket(v)
	return _c
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableBucket(v *string) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetBucket(*v)
	}
	return _c
}

// SetPrefix sets the "prefix" field.
func (_c *ObjectStorageConfigCreate) SetPrefix(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetPrefix(v)
	return _c
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillablePrefix(v *string) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetPrefix(*v)
	}
	return _c
}

// SetForcePathStyle sets the "force_path_style" field.
func (_c *ObjectStorageConfigCreate) SetForcePathStyle(v bool) *ObjectStorageConfigCreate {
	_c.mutation.SetForcePathStyle(v)
	return _c
}

// SetNillableForcePathStyle sets the "force_path_style" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableForcePathStyle(v *bool) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetForcePathStyle(*v)
	}
	return _c
}

// SetPublicBaseURL sets the "public_base_url" field.
func (_c *ObjectStorageConfigCreate) SetPublicBaseURL(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetPublicBaseURL(v)
	return _c
}

// SetNillablePublicBaseURL sets the "public_base_url" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillablePublicBaseURL(v *string) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetPublicBaseURL(*v)
	}
	return _c
}

// SetLocalRoot sets the "local_root" field.
func (_c *ObjectStorageConfigCreate) SetLocalRoot(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetLocalRoot(v)
	return _c
}

// SetNillableLocalRoot sets the "local_root" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableLocalRoot(v *string) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetLocalRoot(*v)
	}
	return _c
}

// SetPublicValue sets the "public_value" field.
func (_c *ObjectStorageConfigCreate) SetPublicValue(v map[string]interface{}) *ObjectStorageConfigCreate {
	_c.mutation.SetPublicValue(v)
	return _c
}

// SetSecretEncrypted sets the "secret_encrypted" field.
func (_c *ObjectStorageConfigCreate) SetSecretEncrypted(v map[string]interface{}) *ObjectStorageConfigCreate {
	_c.mutation.SetSecretEncrypted(v)
	return _c
}

// SetSecretFingerprint sets the "secret_fingerprint" field.
func (_c *ObjectStorageConfigCreate) SetSecretFingerprint(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetSecretFingerprint(v)
	return _c
}

// SetNillableSecretFingerprint sets the "secret_fingerprint" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableSecretFingerprint(v *string) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetSecretFingerprint(*v)
	}
	return _c
}

// SetSecretFields sets the "secret_fields" field.
func (_c *ObjectStorageConfigCreate) SetSecretFields(v []string) *ObjectStorageConfigCreate {
	_c.mutation.SetSecretFields(v)
	return _c
}

// SetLastProbeStatus sets the "last_probe_status" field.
func (_c *ObjectStorageConfigCreate) SetLastProbeStatus(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetLastProbeStatus(v)
	return _c
}

// SetNillableLastProbeStatus sets the "last_probe_status" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableLastProbeStatus(v *string) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetLastProbeStatus(*v)
	}
	return _c
}

// SetLastProbeMessage sets the "last_probe_message" field.
func (_c *ObjectStorageConfigCreate) SetLastProbeMessage(v string) *ObjectStorageConfigCreate {
	_c.mutation.SetLastProbeMessage(v)
	return _c
}

// SetNillableLastProbeMessage sets the "last_probe_message" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableLastProbeMessage(v *string) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetLastProbeMessage(*v)
	}
	return _c
}

// SetLastProbeAt sets the "last_probe_at" field.
func (_c *ObjectStorageConfigCreate) SetLastProbeAt(v time.Time) *ObjectStorageConfigCreate {
	_c.mutation.SetLastProbeAt(v)
	return _c
}

// SetNillableLastProbeAt sets the "last_probe_at" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableLastProbeAt(v *time.Time) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetLastProbeAt(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ObjectStorageConfigCreate) SetVersion(v int64) *ObjectStorageConfigCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableVersion(v *int64) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ObjectStorageConfigCreate) SetUpdatedBy(v int64) *ObjectStorageConfigCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableUpdatedBy(v *int64) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ObjectStorageConfigCreate) SetID(v uuid.UUID) *ObjectStorageConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ObjectStorageConfigCreate) SetNillableID(v *uuid.UUID) *ObjectStorageConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ObjectStorageConfigMutation object of the builder.
func (_c *ObjectStorageConfigCreate) Mutation() *ObjectStorageConfigMutation {
	return _c.mutation
}

// Save creates the ObjectStorageConfig in the database.
func (_c *ObjectStorageConfigCreate) Save(ctx context.Context) (*ObjectStorageConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ObjectStorageConfigCreate) SaveX(ctx context.Context) *ObjectStorageConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObjectStorageConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObjectStorageConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ObjectStorageConfigCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := objectstorageconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := objectstorageconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Driver(); !ok {
		v := objectstorageconfig.DefaultDriver
		_c.mutation.SetDriver(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := objectstorageconfig.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := objectstorageconfig.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ReadEnabled(); !ok {
		v := objectstorageconfig.DefaultReadEnabled
		_c.mutation.SetReadEnabled(v)
	}
	if _, ok := _c.mutation.WriteEnabled(); !ok {
		v := objectstorageconfig.DefaultWriteEnabled
		_c.mutation.SetWriteEnabled(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := objectstorageconfig.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.Prefix(); !ok {
		v := objectstorageconfig.DefaultPrefix
		_c.mutation.SetPrefix(v)
	}
	if _, ok := _c.mutation.ForcePathStyle(); !ok {
		v := objectstorageconfig.DefaultForcePathStyle
		_c.mutation.SetForcePathStyle(v)
	}
	if _, ok := _c.mutation.SecretFingerprint(); !ok {
		v := objectstorageconfig.DefaultSecretFingerprint
		_c.mutation.SetSecretFingerprint(v)
	}
	if _, ok := _c.mutation.LastProbeStatus(); !ok {
		v := objectstorageconfig.DefaultLastProbeStatus
		_c.mutation.SetLastProbeStatus(v)
	}
	if _, ok := _c.mutation.LastProbeMessage(); !ok {
		v := objectstorageconfig.DefaultLastProbeMessage
		_c.mutation.SetLastProbeMessage(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := objectstorageconfig.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		v := objectstorageconfig.DefaultUpdatedBy
		_c.mutation.SetUpdatedBy(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := objectstorageconfig.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ObjectStorageConfigCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ObjectStorageConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ObjectStorageConfig.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "ObjectStorageConfig.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := objectstorageconfig.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ObjectStorageConfig.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := objectstorageconfig.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Driver(); !ok {
		return &ValidationError{Name: "driver", err: errors.New(`ent: missing required field "ObjectStorageConfig.driver"`)}
	}
	if v, ok := _c.mutation.Driver(); ok {
		if err := objectstorageconfig.DriverValidator(v); err != nil {
			return &ValidationError{Name: "driver", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.driver": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ObjectStorageConfig.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := objectstorageconfig.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ObjectStorageConfig.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := objectstorageconfig.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReadEnabled(); !ok {
		return &ValidationError{Name: "read_enabled", err: errors.New(`ent: missing required field "ObjectStorageConfig.read_enabled"`)}
	}
	if _, ok := _c.mutation.WriteEnabled(); !ok {
		return &ValidationError{Name: "write_enabled", err: errors.New(`ent: missing required field "ObjectStorageConfig.write_enabled"`)}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "ObjectStorageConfig.is_default"`)}
	}
	if v, ok := _c.mutation.Endpoint(); ok {
		if err := objectstorageconfig.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.endpoint": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Region(); ok {
		if err := objectstorageconfig.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.region": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Bucket(); ok {
		if err := objectstorageconfig.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.bucket": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Prefix(); !ok {
		return &ValidationError{Name: "prefix", err: errors.New(`ent: missing required field "ObjectStorageConfig.prefix"`)}
	}
	if v, ok := _c.mutation.Prefix(); ok {
		if err := objectstorageconfig.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ForcePathStyle(); !ok {
		return &ValidationError{Name: "force_path_style", err: errors.New(`ent: missing required field "ObjectStorageConfig.force_path_style"`)}
	}
	if v, ok := _c.mutation.PublicBaseURL(); ok {
		if err := objectstorageconfig.PublicBaseURLValidator(v); err != nil {
			return &ValidationError{Name: "public_base_url", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.public_base_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LocalRoot(); ok {
		if err := objectstorageconfig.LocalRootValidator(v); err != nil {
			return &ValidationError{Name: "local_root", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.local_root": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SecretFingerprint(); !ok {
		return &ValidationError{Name: "secret_fingerprint", err: errors.New(`ent: missing required field "ObjectStorageConfig.secret_fingerprint"`)}
	}
	if v, ok := _c.mutation.SecretFingerprint(); ok {
		if err := objectstorageconfig.SecretFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "secret_fingerprint", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.secret_fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastProbeStatus(); !ok {
		return &ValidationError{Name: "last_probe_status", err: errors.New(`ent: missing required field "ObjectStorageConfig.last_probe_status"`)}
	}
	if v, ok := _c.mutation.LastProbeStatus(); ok {
		if err := objectstorageconfig.LastProbeStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_probe_status", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.last_probe_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastProbeMessage(); !ok {
		return &ValidationError{Name: "last_probe_message", err: errors.New(`ent: missing required field "ObjectStorageConfig.last_probe_message"`)}
	}
	if v, ok := _c.mutation.LastProbeMessage(); ok {
		if err := objectstorageconfig.LastProbeMessageValidator(v); err != nil {
			return &ValidationError{Name: "last_probe_message", err: fmt.Errorf(`ent: validator failed for field "ObjectStorageConfig.last_probe_message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ObjectStorageConfig.version"`)}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "ObjectStorageConfig.updated_by"`)}
	}
	return nil
}

func (_c *ObjectStorageConfigCreate) sqlSave(ctx context.Context) (*ObjectStorageConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ObjectStorageConfigCreate) createSpec() (*ObjectStorageConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &ObjectStorageConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(objectstorageconfig.Table, sqlgraph.NewFieldSpec(objectstorageconfig.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(objectstorageconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(objectstorageconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(objectstorageconfig.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(objectstorageconfig.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(objectstorageconfig.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Driver(); ok {
		_spec.SetField(objectstorageconfig.FieldDriver, field.TypeString, value)
		_node.Driver = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(objectstorageconfig.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(objectstorageconfig.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ReadEnabled(); ok {
		_spec.SetField(objectstorageconfig.FieldReadEnabled, field.TypeBool, value)
		_node.ReadEnabled = value
	}
	if value, ok := _c.mutation.WriteEnabled(); ok {
		_spec.SetField(objectstorageconfig.FieldWriteEnabled, field.TypeBool, value)
		_node.WriteEnabled = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(objectstorageconfig.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(objectstorageconfig.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = &value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(objectstorageconfig.FieldRegion, field.TypeString, value)
		_node.Region = &value
	}
	if value, ok := _c.mutation.Bucket(); ok {
		_spec.SetField(objectstorageconfig.FieldBucket, field.TypeString, value)
		_node.Bucket = &value
	}
	if value, ok := _c.mutation.Prefix(); ok {
		_spec.SetField(objectstorageconfig.FieldPrefix, field.TypeString, value)
		_node.Prefix = value
	}
	if value, ok := _c.mutation.ForcePathStyle(); ok {
		_spec.SetField(objectstorageconfig.FieldForcePathStyle, field.TypeBool, value)
		_node.ForcePathStyle = value
	}
	if value, ok := _c.mutation.PublicBaseURL(); ok {
		_spec.SetField(objectstorageconfig.FieldPublicBaseURL, field.TypeString, value)
		_node.PublicBaseURL = &value
	}
	if value, ok := _c.mutation.LocalRoot(); ok {
		_spec.SetField(objectstorageconfig.FieldLocalRoot, field.TypeString, value)
		_node.LocalRoot = &value
	}
	if value, ok := _c.mutation.PublicValue(); ok {
		_spec.SetField(objectstorageconfig.FieldPublicValue, field.TypeJSON, value)
		_node.PublicValue = value
	}
	if value, ok := _c.mutation.SecretEncrypted(); ok {
		_spec.SetField(objectstorageconfig.FieldSecretEncrypted, field.TypeJSON, value)
		_node.SecretEncrypted = value
	}
	if value, ok := _c.mutation.SecretFingerprint(); ok {
		_spec.SetField(objectstorageconfig.FieldSecretFingerprint, field.TypeString, value)
		_node.SecretFingerprint = value
	}
	if value, ok := _c.mutation.SecretFields(); ok {
		_spec.SetField(objectstorageconfig.FieldSecretFields, field.TypeJSON, value)
		_node.SecretFields = value
	}
	if value, ok := _c.mutation.LastProbeStatus(); ok {
		_spec.SetField(objectstorageconfig.FieldLastProbeStatus, field.TypeString, value)
		_node.LastProbeStatus = value
	}
	if value, ok := _c.mutation.LastProbeMessage(); ok {
		_spec.SetField(objectstorageconfig.FieldLastProbeMessage, field.TypeString, value)
		_node.LastProbeMessage = value
	}
	if value, ok := _c.mutation.LastProbeAt(); ok {
		_spec.SetField(objectstorageconfig.FieldLastProbeAt, field.TypeTime, value)
		_node.LastProbeAt = &value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(objectstorageconfig.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(objectstorageconfig.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = value
	}
	return _node, _spec
}

// ObjectStorageConfigCreateBulk is the builder for creating many ObjectStorageConfig entities in bulk.
type ObjectStorageConfigCreateBulk struct {
	config
	err      error
	builders []*ObjectStorageConfigCreate
}

// Save creates the ObjectStorageConfig entities in the database.
func (_c *ObjectStorageConfigCreateBulk) Save(ctx context.Context) ([]*ObjectStorageConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ObjectStorageConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ObjectStorageConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ObjectStorageConfigCreateBulk) SaveX(ctx context.Context) []*ObjectStorageConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObjectStorageConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObjectStorageConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
