// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/paymentwebhookevent"
)

// PaymentWebhookEventCreate is the builder for creating a PaymentWebhookEvent entity.
type PaymentWebhookEventCreate struct {
	config
	mutation *PaymentWebhookEventMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentWebhookEventCreate) SetCreatedAt(v time.Time) *PaymentWebhookEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentWebhookEventCreate) SetNillableCreatedAt(v *time.Time) *PaymentWebhookEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentWebhookEventCreate) SetUpdatedAt(v time.Time) *PaymentWebhookEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentWebhookEventCreate) SetNillableUpdatedAt(v *time.Time) *PaymentWebhookEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *PaymentWebhookEventCreate) SetProvider(v string) *PaymentWebhookEventCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetTradeNo sets the "trade_no" field.
func (_c *PaymentWebhookEventCreate) SetTradeNo(v string) *PaymentWebhookEventCreate {
	_c.mutation.SetTradeNo(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *PaymentWebhookEventCreate) SetEventType(v string) *PaymentWebhookEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_c *PaymentWebhookEventCreate) SetNillableEventType(v *string) *PaymentWebhookEventCreate {
	if v != nil {
		_c.SetEventType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentWebhookEventCreate) SetStatus(v string) *PaymentWebhookEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentWebhookEventCreate) SetNillableStatus(v *string) *PaymentWebhookEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_c *PaymentWebhookEventCreate) SetPaymentOrderID(v int64) *PaymentWebhookEventCreate {
	_c.mutation.SetPaymentOrderID(v)
	return _c
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_c *PaymentWebhookEventCreate) SetNillablePaymentOrderID(v *int64) *PaymentWebhookEventCreate {
	if v != nil {
		_c.SetPaymentOrderID(*v)
	}
	return _c
}

// SetSignature sets the "signature" field.
func (_c *PaymentWebhookEventCreate) SetSignature(v string) *PaymentWebhookEventCreate {
	_c.mutation.SetSignature(v)
	return _c
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_c *PaymentWebhookEventCreate) SetNillableSignature(v *string) *PaymentWebhookEventCreate {
	if v != nil {
		_c.SetSignature(*v)
	}
	return _c
}

// SetHeaders sets the "headers" field.
func (_c *PaymentWebhookEventCreate) SetHeaders(v map[string]interface{}) *PaymentWebhookEventCreate {
	_c.mutation.SetHeaders(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *PaymentWebhookEventCreate) SetPayload(v string) *PaymentWebhookEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_c *PaymentWebhookEventCreate) SetNillablePayload(v *string) *PaymentWebhookEventCreate {
	if v != nil {
		_c.SetPayload(*v)
	}
	return _c
}

// SetProcessedAt sets the "processed_at" field.
func (_c *PaymentWebhookEventCreate) SetProcessedAt(v time.Time) *PaymentWebhookEventCreate {
	_c.mutation.SetProcessedAt(v)
	return _c
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_c *PaymentWebhookEventCreate) SetNillableProcessedAt(v *time.Time) *PaymentWebhookEventCreate {
	if v != nil {
		_c.SetProcessedAt(*v)
	}
	return _c
}

// Mutation returns the PaymentWebhookEventMutation object of the builder.
func (_c *PaymentWebhookEventCreate) Mutation() *PaymentWebhookEventMutation {
	return _c.mutation
}

// Save creates the PaymentWebhookEvent in the database.
func (_c *PaymentWebhookEventCreate) Save(ctx context.Context) (*PaymentWebhookEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentWebhookEventCreate) SaveX(ctx context.Context) *PaymentWebhookEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentWebhookEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentWebhookEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentWebhookEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentwebhookevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentwebhookevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.EventType(); !ok {
		v := paymentwebhookevent.DefaultEventType
		_c.mutation.SetEventType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentwebhookevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentWebhookEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentWebhookEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentWebhookEvent.updated_at"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "PaymentWebhookEvent.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := paymentwebhookevent.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookEvent.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TradeNo(); !ok {
		return &ValidationError{Name: "trade_no", err: errors.New(`ent: missing required field "PaymentWebhookEvent.trade_no"`)}
	}
	if v, ok := _c.mutation.TradeNo(); ok {
		if err := paymentwebhookevent.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookEvent.trade_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "PaymentWebhookEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := paymentwebhookevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentWebhookEvent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentwebhookevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookEvent.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Signature(); ok {
		if err := paymentwebhookevent.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookEvent.signature": %w`, err)}
		}
	}
	return nil
}

func (_c *PaymentWebhookEventCreate) sqlSave(ctx context.Context) (*PaymentWebhookEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentWebhookEventCreate) createSpec() (*PaymentWebhookEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentWebhookEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentwebhookevent.Table, sqlgraph.NewFieldSpec(paymentwebhookevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentwebhookevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentwebhookevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(paymentwebhookevent.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.TradeNo(); ok {
		_spec.SetField(paymentwebhookevent.FieldTradeNo, field.TypeString, value)
		_node.TradeNo = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(paymentwebhookevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentwebhookevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PaymentOrderID(); ok {
		_spec.SetField(paymentwebhookevent.FieldPaymentOrderID, field.TypeInt64, value)
		_node.PaymentOrderID = &value
	}
	if value, ok := _c.mutation.Signature(); ok {
		_spec.SetField(paymentwebhookevent.FieldSignature, field.TypeString, value)
		_node.Signature = &value
	}
	if value, ok := _c.mutation.Headers(); ok {
		_spec.SetField(paymentwebhookevent.FieldHeaders, field.TypeJSON, value)
		_node.Headers = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(paymentwebhookevent.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.ProcessedAt(); ok {
		_spec.SetField(paymentwebhookevent.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = &value
	}
	return _node, _spec
}

// PaymentWebhookEventCreateBulk is the builder for creating many PaymentWebhookEvent entities in bulk.
type PaymentWebhookEventCreateBulk struct {
	config
	err      error
	builders []*PaymentWebhookEventCreate
}

// Save creates the PaymentWebhookEvent entities in the database.
func (_c *PaymentWebhookEventCreateBulk) Save(ctx context.Context) ([]*PaymentWebhookEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentWebhookEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentWebhookEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentWebhookEventCreateBulk) SaveX(ctx context.Context) []*PaymentWebhookEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentWebhookEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentWebhookEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
