// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/project"
	"github.com/google/uuid"
)

// Project is the model entity for the Project schema.
type Project struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// NameKey holds the value of the "name_key" field.
	NameKey string `json:"name_key,omitempty"`
	// IsDefault holds the value of the "is_default" field.
	IsDefault bool `json:"is_default,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// CreateKey holds the value of the "create_key" field.
	CreateKey *string `json:"create_key,omitempty"`
	// DeleteKey holds the value of the "delete_key" field.
	DeleteKey *string `json:"delete_key,omitempty"`
	// DeletedTaskCount holds the value of the "deleted_task_count" field.
	DeletedTaskCount int `json:"deleted_task_count,omitempty"`
	// DeletedAssetCount holds the value of the "deleted_asset_count" field.
	DeletedAssetCount int `json:"deleted_asset_count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectQuery when eager-loading is set.
	Edges        ProjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectEdges holds the relations/edges for other nodes in the graph.
type ProjectEdges struct {
	// ImageTasks holds the value of the image_tasks edge.
	ImageTasks []*ImageTask `json:"image_tasks,omitempty"`
	// ImageResults holds the value of the image_results edge.
	ImageResults []*ImageResult `json:"image_results,omitempty"`
	// VideoTasks holds the value of the video_tasks edge.
	VideoTasks []*VideoTask `json:"video_tasks,omitempty"`
	// MediaAssets holds the value of the media_assets edge.
	MediaAssets []*MediaAsset `json:"media_assets,omitempty"`
	// CreativeCanvases holds the value of the creative_canvases edge.
	CreativeCanvases []*CreativeCanvas `json:"creative_canvases,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// ImageTasksOrErr returns the ImageTasks value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) ImageTasksOrErr() ([]*ImageTask, error) {
	if e.loadedTypes[0] {
		return e.ImageTasks, nil
	}
	return nil, &NotLoadedError{edge: "image_tasks"}
}

// ImageResultsOrErr returns the ImageResults value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) ImageResultsOrErr() ([]*ImageResult, error) {
	if e.loadedTypes[1] {
		return e.ImageResults, nil
	}
	return nil, &NotLoadedError{edge: "image_results"}
}

// VideoTasksOrErr returns the VideoTasks value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) VideoTasksOrErr() ([]*VideoTask, error) {
	if e.loadedTypes[2] {
		return e.VideoTasks, nil
	}
	return nil, &NotLoadedError{edge: "video_tasks"}
}

// MediaAssetsOrErr returns the MediaAssets value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) MediaAssetsOrErr() ([]*MediaAsset, error) {
	if e.loadedTypes[3] {
		return e.MediaAssets, nil
	}
	return nil, &NotLoadedError{edge: "media_assets"}
}

// CreativeCanvasesOrErr returns the CreativeCanvases value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) CreativeCanvasesOrErr() ([]*CreativeCanvas, error) {
	if e.loadedTypes[4] {
		return e.CreativeCanvases, nil
	}
	return nil, &NotLoadedError{edge: "creative_canvases"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Project) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case project.FieldIsDefault:
			values[i] = new(sql.NullBool)
		case project.FieldUserID, project.FieldVersion, project.FieldDeletedTaskCount, project.FieldDeletedAssetCount:
			values[i] = new(sql.NullInt64)
		case project.FieldName, project.FieldNameKey, project.FieldStatus, project.FieldCreateKey, project.FieldDeleteKey:
			values[i] = new(sql.NullString)
		case project.FieldCreatedAt, project.FieldUpdatedAt, project.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case project.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Project fields.
func (_m *Project) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case project.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case project.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case project.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case project.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case project.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case project.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case project.FieldNameKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_key", values[i])
			} else if value.Valid {
				_m.NameKey = value.String
			}
		case project.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		case project.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case project.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case project.FieldCreateKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field create_key", values[i])
			} else if value.Valid {
				_m.CreateKey = new(string)
				*_m.CreateKey = value.String
			}
		case project.FieldDeleteKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delete_key", values[i])
			} else if value.Valid {
				_m.DeleteKey = new(string)
				*_m.DeleteKey = value.String
			}
		case project.FieldDeletedTaskCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_task_count", values[i])
			} else if value.Valid {
				_m.DeletedTaskCount = int(value.Int64)
			}
		case project.FieldDeletedAssetCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_asset_count", values[i])
			} else if value.Valid {
				_m.DeletedAssetCount = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Project.
// This includes values selected through modifiers, order, etc.
func (_m *Project) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryImageTasks queries the "image_tasks" edge of the Project entity.
func (_m *Project) QueryImageTasks() *ImageTaskQuery {
	return NewProjectClient(_m.config).QueryImageTasks(_m)
}

// QueryImageResults queries the "image_results" edge of the Project entity.
func (_m *Project) QueryImageResults() *ImageResultQuery {
	return NewProjectClient(_m.config).QueryImageResults(_m)
}

// QueryVideoTasks queries the "video_tasks" edge of the Project entity.
func (_m *Project) QueryVideoTasks() *VideoTaskQuery {
	return NewProjectClient(_m.config).QueryVideoTasks(_m)
}

// QueryMediaAssets queries the "media_assets" edge of the Project entity.
func (_m *Project) QueryMediaAssets() *MediaAssetQuery {
	return NewProjectClient(_m.config).QueryMediaAssets(_m)
}

// QueryCreativeCanvases queries the "creative_canvases" edge of the Project entity.
func (_m *Project) QueryCreativeCanvases() *CreativeCanvasQuery {
	return NewProjectClient(_m.config).QueryCreativeCanvases(_m)
}

// Update returns a builder for updating this Project.
// Note that you need to call Project.Unwrap() before calling this method if this Project
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Project) Update() *ProjectUpdateOne {
	return NewProjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Project entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Project) Unwrap() *Project {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Project is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Project) String() string {
	var builder strings.Builder
	builder.WriteString("Project(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("name_key=")
	builder.WriteString(_m.NameKey)
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	if v := _m.CreateKey; v != nil {
		builder.WriteString("create_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DeleteKey; v != nil {
		builder.WriteString("delete_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("deleted_task_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedTaskCount))
	builder.WriteString(", ")
	builder.WriteString("deleted_asset_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAssetCount))
	builder.WriteByte(')')
	return builder.String()
}

// Projects is a parsable slice of Project.
type Projects []*Project
