// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/predicate"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/routemodelvisibilitygroup"
)

// RouteModelVisibilityGroupDelete is the builder for deleting a RouteModelVisibilityGroup entity.
type RouteModelVisibilityGroupDelete struct {
	config
	hooks    []Hook
	mutation *RouteModelVisibilityGroupMutation
}

// Where appends a list predicates to the RouteModelVisibilityGroupDelete builder.
func (_d *RouteModelVisibilityGroupDelete) Where(ps ...predicate.RouteModelVisibilityGroup) *RouteModelVisibilityGroupDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RouteModelVisibilityGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RouteModelVisibilityGroupDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RouteModelVisibilityGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(routemodelvisibilitygroup.Table, sqlgraph.NewFieldSpec(routemodelvisibilitygroup.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RouteModelVisibilityGroupDeleteOne is the builder for deleting a single RouteModelVisibilityGroup entity.
type RouteModelVisibilityGroupDeleteOne struct {
	_d *RouteModelVisibilityGroupDelete
}

// Where appends a list predicates to the RouteModelVisibilityGroupDelete builder.
func (_d *RouteModelVisibilityGroupDeleteOne) Where(ps ...predicate.RouteModelVisibilityGroup) *RouteModelVisibilityGroupDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RouteModelVisibilityGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{routemodelvisibilitygroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RouteModelVisibilityGroupDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
