// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/secureconfig"
)

// SecureConfig is the model entity for the SecureConfig schema.
type SecureConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ConfigCategory holds the value of the "config_category" field.
	ConfigCategory string `json:"config_category,omitempty"`
	// ConfigKey holds the value of the "config_key" field.
	ConfigKey string `json:"config_key,omitempty"`
	// PublicValue holds the value of the "public_value" field.
	PublicValue map[string]interface{} `json:"public_value,omitempty"`
	// SecretEncrypted holds the value of the "secret_encrypted" field.
	SecretEncrypted map[string]interface{} `json:"secret_encrypted,omitempty"`
	// SecretFingerprint holds the value of the "secret_fingerprint" field.
	SecretFingerprint string `json:"secret_fingerprint,omitempty"`
	// SecretFields holds the value of the "secret_fields" field.
	SecretFields []string `json:"secret_fields,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy    int64 `json:"updated_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SecureConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case secureconfig.FieldPublicValue, secureconfig.FieldSecretEncrypted, secureconfig.FieldSecretFields:
			values[i] = new([]byte)
		case secureconfig.FieldID, secureconfig.FieldVersion, secureconfig.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case secureconfig.FieldConfigCategory, secureconfig.FieldConfigKey, secureconfig.FieldSecretFingerprint:
			values[i] = new(sql.NullString)
		case secureconfig.FieldCreatedAt, secureconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SecureConfig fields.
func (_m *SecureConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case secureconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case secureconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case secureconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case secureconfig.FieldConfigCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_category", values[i])
			} else if value.Valid {
				_m.ConfigCategory = value.String
			}
		case secureconfig.FieldConfigKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_key", values[i])
			} else if value.Valid {
				_m.ConfigKey = value.String
			}
		case secureconfig.FieldPublicValue:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field public_value", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PublicValue); err != nil {
					return fmt.Errorf("unmarshal field public_value: %w", err)
				}
			}
		case secureconfig.FieldSecretEncrypted:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field secret_encrypted", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SecretEncrypted); err != nil {
					return fmt.Errorf("unmarshal field secret_encrypted: %w", err)
				}
			}
		case secureconfig.FieldSecretFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_fingerprint", values[i])
			} else if value.Valid {
				_m.SecretFingerprint = value.String
			}
		case secureconfig.FieldSecretFields:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field secret_fields", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SecretFields); err != nil {
					return fmt.Errorf("unmarshal field secret_fields: %w", err)
				}
			}
		case secureconfig.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case secureconfig.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SecureConfig.
// This includes values selected through modifiers, order, etc.
func (_m *SecureConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SecureConfig.
// Note that you need to call SecureConfig.Unwrap() before calling this method if this SecureConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SecureConfig) Update() *SecureConfigUpdateOne {
	return NewSecureConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SecureConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SecureConfig) Unwrap() *SecureConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SecureConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SecureConfig) String() string {
	var builder strings.Builder
	builder.WriteString("SecureConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("config_category=")
	builder.WriteString(_m.ConfigCategory)
	builder.WriteString(", ")
	builder.WriteString("config_key=")
	builder.WriteString(_m.ConfigKey)
	builder.WriteString(", ")
	builder.WriteString("public_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicValue))
	builder.WriteString(", ")
	builder.WriteString("secret_encrypted=")
	builder.WriteString(fmt.Sprintf("%v", _m.SecretEncrypted))
	builder.WriteString(", ")
	builder.WriteString("secret_fingerprint=")
	builder.WriteString(_m.SecretFingerprint)
	builder.WriteString(", ")
	builder.WriteString("secret_fields=")
	builder.WriteString(fmt.Sprintf("%v", _m.SecretFields))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteByte(')')
	return builder.String()
}

// SecureConfigs is a parsable slice of SecureConfig.
type SecureConfigs []*SecureConfig
