// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/storagemigrationjob"
	"github.com/google/uuid"
)

// StorageMigrationJobCreate is the builder for creating a StorageMigrationJob entity.
type StorageMigrationJobCreate struct {
	config
	mutation *StorageMigrationJobMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *StorageMigrationJobCreate) SetCreatedAt(v time.Time) *StorageMigrationJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableCreatedAt(v *time.Time) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StorageMigrationJobCreate) SetUpdatedAt(v time.Time) *StorageMigrationJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableUpdatedAt(v *time.Time) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSourceStorageConfigID sets the "source_storage_config_id" field.
func (_c *StorageMigrationJobCreate) SetSourceStorageConfigID(v int64) *StorageMigrationJobCreate {
	_c.mutation.SetSourceStorageConfigID(v)
	return _c
}

// SetNillableSourceStorageConfigID sets the "source_storage_config_id" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableSourceStorageConfigID(v *int64) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetSourceStorageConfigID(*v)
	}
	return _c
}

// SetTargetStorageConfigID sets the "target_storage_config_id" field.
func (_c *StorageMigrationJobCreate) SetTargetStorageConfigID(v int64) *StorageMigrationJobCreate {
	_c.mutation.SetTargetStorageConfigID(v)
	return _c
}

// SetNillableTargetStorageConfigID sets the "target_storage_config_id" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableTargetStorageConfigID(v *int64) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetTargetStorageConfigID(*v)
	}
	return _c
}

// SetSourceLegacyDriver sets the "source_legacy_driver" field.
func (_c *StorageMigrationJobCreate) SetSourceLegacyDriver(v string) *StorageMigrationJobCreate {
	_c.mutation.SetSourceLegacyDriver(v)
	return _c
}

// SetNillableSourceLegacyDriver sets the "source_legacy_driver" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableSourceLegacyDriver(v *string) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetSourceLegacyDriver(*v)
	}
	return _c
}

// SetScope sets the "scope" field.
func (_c *StorageMigrationJobCreate) SetScope(v map[string]interface{}) *StorageMigrationJobCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetDryRun sets the "dry_run" field.
func (_c *StorageMigrationJobCreate) SetDryRun(v bool) *StorageMigrationJobCreate {
	_c.mutation.SetDryRun(v)
	return _c
}

// SetNillableDryRun sets the "dry_run" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableDryRun(v *bool) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetDryRun(*v)
	}
	return _c
}

// SetUpdateRecords sets the "update_records" field.
func (_c *StorageMigrationJobCreate) SetUpdateRecords(v bool) *StorageMigrationJobCreate {
	_c.mutation.SetUpdateRecords(v)
	return _c
}

// SetNillableUpdateRecords sets the "update_records" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableUpdateRecords(v *bool) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetUpdateRecords(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *StorageMigrationJobCreate) SetStatus(v string) *StorageMigrationJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableStatus(v *string) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTotalItems sets the "total_items" field.
func (_c *StorageMigrationJobCreate) SetTotalItems(v int64) *StorageMigrationJobCreate {
	_c.mutation.SetTotalItems(v)
	return _c
}

// SetNillableTotalItems sets the "total_items" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableTotalItems(v *int64) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetTotalItems(*v)
	}
	return _c
}

// SetProcessedItems sets the "processed_items" field.
func (_c *StorageMigrationJobCreate) SetProcessedItems(v int64) *StorageMigrationJobCreate {
	_c.mutation.SetProcessedItems(v)
	return _c
}

// SetNillableProcessedItems sets the "processed_items" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableProcessedItems(v *int64) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetProcessedItems(*v)
	}
	return _c
}

// SetFailedItems sets the "failed_items" field.
func (_c *StorageMigrationJobCreate) SetFailedItems(v int64) *StorageMigrationJobCreate {
	_c.mutation.SetFailedItems(v)
	return _c
}

// SetNillableFailedItems sets the "failed_items" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableFailedItems(v *int64) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetFailedItems(*v)
	}
	return _c
}

// SetTotalBytes sets the "total_bytes" field.
func (_c *StorageMigrationJobCreate) SetTotalBytes(v int64) *StorageMigrationJobCreate {
	_c.mutation.SetTotalBytes(v)
	return _c
}

// SetNillableTotalBytes sets the "total_bytes" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableTotalBytes(v *int64) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetTotalBytes(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *StorageMigrationJobCreate) SetLastError(v string) *StorageMigrationJobCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableLastError(v *string) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *StorageMigrationJobCreate) SetCreatedBy(v int64) *StorageMigrationJobCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableCreatedBy(v *int64) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *StorageMigrationJobCreate) SetStartedAt(v time.Time) *StorageMigrationJobCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableStartedAt(v *time.Time) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *StorageMigrationJobCreate) SetFinishedAt(v time.Time) *StorageMigrationJobCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableFinishedAt(v *time.Time) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StorageMigrationJobCreate) SetID(v uuid.UUID) *StorageMigrationJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *StorageMigrationJobCreate) SetNillableID(v *uuid.UUID) *StorageMigrationJobCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the StorageMigrationJobMutation object of the builder.
func (_c *StorageMigrationJobCreate) Mutation() *StorageMigrationJobMutation {
	return _c.mutation
}

// Save creates the StorageMigrationJob in the database.
func (_c *StorageMigrationJobCreate) Save(ctx context.Context) (*StorageMigrationJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StorageMigrationJobCreate) SaveX(ctx context.Context) *StorageMigrationJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageMigrationJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageMigrationJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StorageMigrationJobCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := storagemigrationjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := storagemigrationjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SourceLegacyDriver(); !ok {
		v := storagemigrationjob.DefaultSourceLegacyDriver
		_c.mutation.SetSourceLegacyDriver(v)
	}
	if _, ok := _c.mutation.DryRun(); !ok {
		v := storagemigrationjob.DefaultDryRun
		_c.mutation.SetDryRun(v)
	}
	if _, ok := _c.mutation.UpdateRecords(); !ok {
		v := storagemigrationjob.DefaultUpdateRecords
		_c.mutation.SetUpdateRecords(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := storagemigrationjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalItems(); !ok {
		v := storagemigrationjob.DefaultTotalItems
		_c.mutation.SetTotalItems(v)
	}
	if _, ok := _c.mutation.ProcessedItems(); !ok {
		v := storagemigrationjob.DefaultProcessedItems
		_c.mutation.SetProcessedItems(v)
	}
	if _, ok := _c.mutation.FailedItems(); !ok {
		v := storagemigrationjob.DefaultFailedItems
		_c.mutation.SetFailedItems(v)
	}
	if _, ok := _c.mutation.TotalBytes(); !ok {
		v := storagemigrationjob.DefaultTotalBytes
		_c.mutation.SetTotalBytes(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := storagemigrationjob.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := storagemigrationjob.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := storagemigrationjob.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StorageMigrationJobCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StorageMigrationJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "StorageMigrationJob.updated_at"`)}
	}
	if _, ok := _c.mutation.SourceLegacyDriver(); !ok {
		return &ValidationError{Name: "source_legacy_driver", err: errors.New(`ent: missing required field "StorageMigrationJob.source_legacy_driver"`)}
	}
	if v, ok := _c.mutation.SourceLegacyDriver(); ok {
		if err := storagemigrationjob.SourceLegacyDriverValidator(v); err != nil {
			return &ValidationError{Name: "source_legacy_driver", err: fmt.Errorf(`ent: validator failed for field "StorageMigrationJob.source_legacy_driver": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DryRun(); !ok {
		return &ValidationError{Name: "dry_run", err: errors.New(`ent: missing required field "StorageMigrationJob.dry_run"`)}
	}
	if _, ok := _c.mutation.UpdateRecords(); !ok {
		return &ValidationError{Name: "update_records", err: errors.New(`ent: missing required field "StorageMigrationJob.update_records"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "StorageMigrationJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := storagemigrationjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StorageMigrationJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalItems(); !ok {
		return &ValidationError{Name: "total_items", err: errors.New(`ent: missing required field "StorageMigrationJob.total_items"`)}
	}
	if _, ok := _c.mutation.ProcessedItems(); !ok {
		return &ValidationError{Name: "processed_items", err: errors.New(`ent: missing required field "StorageMigrationJob.processed_items"`)}
	}
	if _, ok := _c.mutation.FailedItems(); !ok {
		return &ValidationError{Name: "failed_items", err: errors.New(`ent: missing required field "StorageMigrationJob.failed_items"`)}
	}
	if _, ok := _c.mutation.TotalBytes(); !ok {
		return &ValidationError{Name: "total_bytes", err: errors.New(`ent: missing required field "StorageMigrationJob.total_bytes"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "StorageMigrationJob.last_error"`)}
	}
	if v, ok := _c.mutation.LastError(); ok {
		if err := storagemigrationjob.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "StorageMigrationJob.last_error": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "StorageMigrationJob.created_by"`)}
	}
	return nil
}

func (_c *StorageMigrationJobCreate) sqlSave(ctx context.Context) (*StorageMigrationJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StorageMigrationJobCreate) createSpec() (*StorageMigrationJob, *sqlgraph.CreateSpec) {
	var (
		_node = &StorageMigrationJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(storagemigrationjob.Table, sqlgraph.NewFieldSpec(storagemigrationjob.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(storagemigrationjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(storagemigrationjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SourceStorageConfigID(); ok {
		_spec.SetField(storagemigrationjob.FieldSourceStorageConfigID, field.TypeInt64, value)
		_node.SourceStorageConfigID = &value
	}
	if value, ok := _c.mutation.TargetStorageConfigID(); ok {
		_spec.SetField(storagemigrationjob.FieldTargetStorageConfigID, field.TypeInt64, value)
		_node.TargetStorageConfigID = &value
	}
	if value, ok := _c.mutation.SourceLegacyDriver(); ok {
		_spec.SetField(storagemigrationjob.FieldSourceLegacyDriver, field.TypeString, value)
		_node.SourceLegacyDriver = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(storagemigrationjob.FieldScope, field.TypeJSON, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.DryRun(); ok {
		_spec.SetField(storagemigrationjob.FieldDryRun, field.TypeBool, value)
		_node.DryRun = value
	}
	if value, ok := _c.mutation.UpdateRecords(); ok {
		_spec.SetField(storagemigrationjob.FieldUpdateRecords, field.TypeBool, value)
		_node.UpdateRecords = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(storagemigrationjob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TotalItems(); ok {
		_spec.SetField(storagemigrationjob.FieldTotalItems, field.TypeInt64, value)
		_node.TotalItems = value
	}
	if value, ok := _c.mutation.ProcessedItems(); ok {
		_spec.SetField(storagemigrationjob.FieldProcessedItems, field.TypeInt64, value)
		_node.ProcessedItems = value
	}
	if value, ok := _c.mutation.FailedItems(); ok {
		_spec.SetField(storagemigrationjob.FieldFailedItems, field.TypeInt64, value)
		_node.FailedItems = value
	}
	if value, ok := _c.mutation.TotalBytes(); ok {
		_spec.SetField(storagemigrationjob.FieldTotalBytes, field.TypeInt64, value)
		_node.TotalBytes = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(storagemigrationjob.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(storagemigrationjob.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(storagemigrationjob.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(storagemigrationjob.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	return _node, _spec
}

// StorageMigrationJobCreateBulk is the builder for creating many StorageMigrationJob entities in bulk.
type StorageMigrationJobCreateBulk struct {
	config
	err      error
	builders []*StorageMigrationJobCreate
}

// Save creates the StorageMigrationJob entities in the database.
func (_c *StorageMigrationJobCreateBulk) Save(ctx context.Context) ([]*StorageMigrationJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StorageMigrationJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StorageMigrationJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StorageMigrationJobCreateBulk) SaveX(ctx context.Context) []*StorageMigrationJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageMigrationJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageMigrationJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
