// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/predicate"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/storagemigrationjob"
)

// StorageMigrationJobDelete is the builder for deleting a StorageMigrationJob entity.
type StorageMigrationJobDelete struct {
	config
	hooks    []Hook
	mutation *StorageMigrationJobMutation
}

// Where appends a list predicates to the StorageMigrationJobDelete builder.
func (_d *StorageMigrationJobDelete) Where(ps ...predicate.StorageMigrationJob) *StorageMigrationJobDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *StorageMigrationJobDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StorageMigrationJobDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *StorageMigrationJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(storagemigrationjob.Table, sqlgraph.NewFieldSpec(storagemigrationjob.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// StorageMigrationJobDeleteOne is the builder for deleting a single StorageMigrationJob entity.
type StorageMigrationJobDeleteOne struct {
	_d *StorageMigrationJobDelete
}

// Where appends a list predicates to the StorageMigrationJobDelete builder.
func (_d *StorageMigrationJobDeleteOne) Where(ps ...predicate.StorageMigrationJob) *StorageMigrationJobDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *StorageMigrationJobDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{storagemigrationjob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StorageMigrationJobDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
