// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/predicate"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserUpdate) SetDeletedAt(v time.Time) *UserUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDeletedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserUpdate) ClearDeletedAt() *UserUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *UserUpdate) ClearPasswordHash() *UserUpdate {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *UserUpdate) SetNickname(v string) *UserUpdate {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *UserUpdate) SetNillableNickname(v *string) *UserUpdate {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetBio sets the "bio" field.
func (_u *UserUpdate) SetBio(v string) *UserUpdate {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *UserUpdate) SetNillableBio(v *string) *UserUpdate {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// SetAvatarObjectKey sets the "avatar_object_key" field.
func (_u *UserUpdate) SetAvatarObjectKey(v string) *UserUpdate {
	_u.mutation.SetAvatarObjectKey(v)
	return _u
}

// SetNillableAvatarObjectKey sets the "avatar_object_key" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAvatarObjectKey(v *string) *UserUpdate {
	if v != nil {
		_u.SetAvatarObjectKey(*v)
	}
	return _u
}

// ClearAvatarObjectKey clears the value of the "avatar_object_key" field.
func (_u *UserUpdate) ClearAvatarObjectKey() *UserUpdate {
	_u.mutation.ClearAvatarObjectKey()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserUpdate) SetStatus(v string) *UserUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserUpdate) SetNillableStatus(v *string) *UserUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserGroupID sets the "user_group_id" field.
func (_u *UserUpdate) SetUserGroupID(v int64) *UserUpdate {
	_u.mutation.ResetUserGroupID()
	_u.mutation.SetUserGroupID(v)
	return _u
}

// SetNillableUserGroupID sets the "user_group_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserGroupID(v *int64) *UserUpdate {
	if v != nil {
		_u.SetUserGroupID(*v)
	}
	return _u
}

// AddUserGroupID adds value to the "user_group_id" field.
func (_u *UserUpdate) AddUserGroupID(v int64) *UserUpdate {
	_u.mutation.AddUserGroupID(v)
	return _u
}

// SetTokenVersion sets the "token_version" field.
func (_u *UserUpdate) SetTokenVersion(v int) *UserUpdate {
	_u.mutation.ResetTokenVersion()
	_u.mutation.SetTokenVersion(v)
	return _u
}

// SetNillableTokenVersion sets the "token_version" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTokenVersion(v *int) *UserUpdate {
	if v != nil {
		_u.SetTokenVersion(*v)
	}
	return _u
}

// AddTokenVersion adds value to the "token_version" field.
func (_u *UserUpdate) AddTokenVersion(v int) *UserUpdate {
	_u.mutation.AddTokenVersion(v)
	return _u
}

// SetDefaultLocale sets the "default_locale" field.
func (_u *UserUpdate) SetDefaultLocale(v string) *UserUpdate {
	_u.mutation.SetDefaultLocale(v)
	return _u
}

// SetNillableDefaultLocale sets the "default_locale" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDefaultLocale(v *string) *UserUpdate {
	if v != nil {
		_u.SetDefaultLocale(*v)
	}
	return _u
}

// SetTheme sets the "theme" field.
func (_u *UserUpdate) SetTheme(v string) *UserUpdate {
	_u.mutation.SetTheme(v)
	return _u
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTheme(v *string) *UserUpdate {
	if v != nil {
		_u.SetTheme(*v)
	}
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nickname(); ok {
		if err := user.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "User.nickname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bio(); ok {
		if err := user.BioValidator(v); err != nil {
			return &ValidationError{Name: "bio", err: fmt.Errorf(`ent: validator failed for field "User.bio": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvatarObjectKey(); ok {
		if err := user.AvatarObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "avatar_object_key", err: fmt.Errorf(`ent: validator failed for field "User.avatar_object_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := user.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "User.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultLocale(); ok {
		if err := user.DefaultLocaleValidator(v); err != nil {
			return &ValidationError{Name: "default_locale", err: fmt.Errorf(`ent: validator failed for field "User.default_locale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Theme(); ok {
		if err := user.ThemeValidator(v); err != nil {
			return &ValidationError{Name: "theme", err: fmt.Errorf(`ent: validator failed for field "User.theme": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(user.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(user.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(user.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(user.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(user.FieldBio, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarObjectKey(); ok {
		_spec.SetField(user.FieldAvatarObjectKey, field.TypeString, value)
	}
	if _u.mutation.AvatarObjectKeyCleared() {
		_spec.ClearField(user.FieldAvatarObjectKey, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(user.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserGroupID(); ok {
		_spec.SetField(user.FieldUserGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserGroupID(); ok {
		_spec.AddField(user.FieldUserGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TokenVersion(); ok {
		_spec.SetField(user.FieldTokenVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenVersion(); ok {
		_spec.AddField(user.FieldTokenVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DefaultLocale(); ok {
		_spec.SetField(user.FieldDefaultLocale, field.TypeString, value)
	}
	if value, ok := _u.mutation.Theme(); ok {
		_spec.SetField(user.FieldTheme, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserUpdateOne) SetDeletedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDeletedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserUpdateOne) ClearDeletedAt() *UserUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *UserUpdateOne) ClearPasswordHash() *UserUpdateOne {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *UserUpdateOne) SetNickname(v string) *UserUpdateOne {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableNickname(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetBio sets the "bio" field.
func (_u *UserUpdateOne) SetBio(v string) *UserUpdateOne {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableBio(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// SetAvatarObjectKey sets the "avatar_object_key" field.
func (_u *UserUpdateOne) SetAvatarObjectKey(v string) *UserUpdateOne {
	_u.mutation.SetAvatarObjectKey(v)
	return _u
}

// SetNillableAvatarObjectKey sets the "avatar_object_key" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAvatarObjectKey(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAvatarObjectKey(*v)
	}
	return _u
}

// ClearAvatarObjectKey clears the value of the "avatar_object_key" field.
func (_u *UserUpdateOne) ClearAvatarObjectKey() *UserUpdateOne {
	_u.mutation.ClearAvatarObjectKey()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserUpdateOne) SetStatus(v string) *UserUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableStatus(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserGroupID sets the "user_group_id" field.
func (_u *UserUpdateOne) SetUserGroupID(v int64) *UserUpdateOne {
	_u.mutation.ResetUserGroupID()
	_u.mutation.SetUserGroupID(v)
	return _u
}

// SetNillableUserGroupID sets the "user_group_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserGroupID(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetUserGroupID(*v)
	}
	return _u
}

// AddUserGroupID adds value to the "user_group_id" field.
func (_u *UserUpdateOne) AddUserGroupID(v int64) *UserUpdateOne {
	_u.mutation.AddUserGroupID(v)
	return _u
}

// SetTokenVersion sets the "token_version" field.
func (_u *UserUpdateOne) SetTokenVersion(v int) *UserUpdateOne {
	_u.mutation.ResetTokenVersion()
	_u.mutation.SetTokenVersion(v)
	return _u
}

// SetNillableTokenVersion sets the "token_version" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTokenVersion(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetTokenVersion(*v)
	}
	return _u
}

// AddTokenVersion adds value to the "token_version" field.
func (_u *UserUpdateOne) AddTokenVersion(v int) *UserUpdateOne {
	_u.mutation.AddTokenVersion(v)
	return _u
}

// SetDefaultLocale sets the "default_locale" field.
func (_u *UserUpdateOne) SetDefaultLocale(v string) *UserUpdateOne {
	_u.mutation.SetDefaultLocale(v)
	return _u
}

// SetNillableDefaultLocale sets the "default_locale" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDefaultLocale(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetDefaultLocale(*v)
	}
	return _u
}

// SetTheme sets the "theme" field.
func (_u *UserUpdateOne) SetTheme(v string) *UserUpdateOne {
	_u.mutation.SetTheme(v)
	return _u
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTheme(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetTheme(*v)
	}
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nickname(); ok {
		if err := user.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "User.nickname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bio(); ok {
		if err := user.BioValidator(v); err != nil {
			return &ValidationError{Name: "bio", err: fmt.Errorf(`ent: validator failed for field "User.bio": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvatarObjectKey(); ok {
		if err := user.AvatarObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "avatar_object_key", err: fmt.Errorf(`ent: validator failed for field "User.avatar_object_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := user.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "User.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultLocale(); ok {
		if err := user.DefaultLocaleValidator(v); err != nil {
			return &ValidationError{Name: "default_locale", err: fmt.Errorf(`ent: validator failed for field "User.default_locale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Theme(); ok {
		if err := user.ThemeValidator(v); err != nil {
			return &ValidationError{Name: "theme", err: fmt.Errorf(`ent: validator failed for field "User.theme": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(user.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(user.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(user.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(user.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(user.FieldBio, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarObjectKey(); ok {
		_spec.SetField(user.FieldAvatarObjectKey, field.TypeString, value)
	}
	if _u.mutation.AvatarObjectKeyCleared() {
		_spec.ClearField(user.FieldAvatarObjectKey, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(user.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserGroupID(); ok {
		_spec.SetField(user.FieldUserGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserGroupID(); ok {
		_spec.AddField(user.FieldUserGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TokenVersion(); ok {
		_spec.SetField(user.FieldTokenVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenVersion(); ok {
		_spec.AddField(user.FieldTokenVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DefaultLocale(); ok {
		_spec.SetField(user.FieldDefaultLocale, field.TypeString, value)
	}
	if value, ok := _u.mutation.Theme(); ok {
		_spec.SetField(user.FieldTheme, field.TypeString, value)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
