// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/videoprovidercallbackevent"
	"github.com/google/uuid"
)

// VideoProviderCallbackEventCreate is the builder for creating a VideoProviderCallbackEvent entity.
type VideoProviderCallbackEventCreate struct {
	config
	mutation *VideoProviderCallbackEventMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *VideoProviderCallbackEventCreate) SetCreatedAt(v time.Time) *VideoProviderCallbackEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VideoProviderCallbackEventCreate) SetNillableCreatedAt(v *time.Time) *VideoProviderCallbackEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VideoProviderCallbackEventCreate) SetUpdatedAt(v time.Time) *VideoProviderCallbackEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VideoProviderCallbackEventCreate) SetNillableUpdatedAt(v *time.Time) *VideoProviderCallbackEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProviderCode sets the "provider_code" field.
func (_c *VideoProviderCallbackEventCreate) SetProviderCode(v string) *VideoProviderCallbackEventCreate {
	_c.mutation.SetProviderCode(v)
	return _c
}

// SetModelAccountID sets the "model_account_id" field.
func (_c *VideoProviderCallbackEventCreate) SetModelAccountID(v int64) *VideoProviderCallbackEventCreate {
	_c.mutation.SetModelAccountID(v)
	return _c
}

// SetProviderEventID sets the "provider_event_id" field.
func (_c *VideoProviderCallbackEventCreate) SetProviderEventID(v string) *VideoProviderCallbackEventCreate {
	_c.mutation.SetProviderEventID(v)
	return _c
}

// SetProviderJobID sets the "provider_job_id" field.
func (_c *VideoProviderCallbackEventCreate) SetProviderJobID(v string) *VideoProviderCallbackEventCreate {
	_c.mutation.SetProviderJobID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *VideoProviderCallbackEventCreate) SetStatus(v string) *VideoProviderCallbackEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VideoProviderCallbackEventCreate) SetNillableStatus(v *string) *VideoProviderCallbackEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPayloadSnapshot sets the "payload_snapshot" field.
func (_c *VideoProviderCallbackEventCreate) SetPayloadSnapshot(v map[string]interface{}) *VideoProviderCallbackEventCreate {
	_c.mutation.SetPayloadSnapshot(v)
	return _c
}

// SetReceivedAt sets the "received_at" field.
func (_c *VideoProviderCallbackEventCreate) SetReceivedAt(v time.Time) *VideoProviderCallbackEventCreate {
	_c.mutation.SetReceivedAt(v)
	return _c
}

// SetProcessedAt sets the "processed_at" field.
func (_c *VideoProviderCallbackEventCreate) SetProcessedAt(v time.Time) *VideoProviderCallbackEventCreate {
	_c.mutation.SetProcessedAt(v)
	return _c
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_c *VideoProviderCallbackEventCreate) SetNillableProcessedAt(v *time.Time) *VideoProviderCallbackEventCreate {
	if v != nil {
		_c.SetProcessedAt(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *VideoProviderCallbackEventCreate) SetErrorCode(v string) *VideoProviderCallbackEventCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *VideoProviderCallbackEventCreate) SetNillableErrorCode(v *string) *VideoProviderCallbackEventCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *VideoProviderCallbackEventCreate) SetErrorMessage(v string) *VideoProviderCallbackEventCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *VideoProviderCallbackEventCreate) SetNillableErrorMessage(v *string) *VideoProviderCallbackEventCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VideoProviderCallbackEventCreate) SetID(v uuid.UUID) *VideoProviderCallbackEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *VideoProviderCallbackEventCreate) SetNillableID(v *uuid.UUID) *VideoProviderCallbackEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the VideoProviderCallbackEventMutation object of the builder.
func (_c *VideoProviderCallbackEventCreate) Mutation() *VideoProviderCallbackEventMutation {
	return _c.mutation
}

// Save creates the VideoProviderCallbackEvent in the database.
func (_c *VideoProviderCallbackEventCreate) Save(ctx context.Context) (*VideoProviderCallbackEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VideoProviderCallbackEventCreate) SaveX(ctx context.Context) *VideoProviderCallbackEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoProviderCallbackEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoProviderCallbackEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VideoProviderCallbackEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := videoprovidercallbackevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := videoprovidercallbackevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := videoprovidercallbackevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := videoprovidercallbackevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VideoProviderCallbackEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VideoProviderCallbackEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VideoProviderCallbackEvent.updated_at"`)}
	}
	if _, ok := _c.mutation.ProviderCode(); !ok {
		return &ValidationError{Name: "provider_code", err: errors.New(`ent: missing required field "VideoProviderCallbackEvent.provider_code"`)}
	}
	if v, ok := _c.mutation.ProviderCode(); ok {
		if err := videoprovidercallbackevent.ProviderCodeValidator(v); err != nil {
			return &ValidationError{Name: "provider_code", err: fmt.Errorf(`ent: validator failed for field "VideoProviderCallbackEvent.provider_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelAccountID(); !ok {
		return &ValidationError{Name: "model_account_id", err: errors.New(`ent: missing required field "VideoProviderCallbackEvent.model_account_id"`)}
	}
	if v, ok := _c.mutation.ModelAccountID(); ok {
		if err := videoprovidercallbackevent.ModelAccountIDValidator(v); err != nil {
			return &ValidationError{Name: "model_account_id", err: fmt.Errorf(`ent: validator failed for field "VideoProviderCallbackEvent.model_account_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderEventID(); !ok {
		return &ValidationError{Name: "provider_event_id", err: errors.New(`ent: missing required field "VideoProviderCallbackEvent.provider_event_id"`)}
	}
	if v, ok := _c.mutation.ProviderEventID(); ok {
		if err := videoprovidercallbackevent.ProviderEventIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_event_id", err: fmt.Errorf(`ent: validator failed for field "VideoProviderCallbackEvent.provider_event_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderJobID(); !ok {
		return &ValidationError{Name: "provider_job_id", err: errors.New(`ent: missing required field "VideoProviderCallbackEvent.provider_job_id"`)}
	}
	if v, ok := _c.mutation.ProviderJobID(); ok {
		if err := videoprovidercallbackevent.ProviderJobIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_job_id", err: fmt.Errorf(`ent: validator failed for field "VideoProviderCallbackEvent.provider_job_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "VideoProviderCallbackEvent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := videoprovidercallbackevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoProviderCallbackEvent.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PayloadSnapshot(); !ok {
		return &ValidationError{Name: "payload_snapshot", err: errors.New(`ent: missing required field "VideoProviderCallbackEvent.payload_snapshot"`)}
	}
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		return &ValidationError{Name: "received_at", err: errors.New(`ent: missing required field "VideoProviderCallbackEvent.received_at"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := videoprovidercallbackevent.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "VideoProviderCallbackEvent.error_code": %w`, err)}
		}
	}
	return nil
}

func (_c *VideoProviderCallbackEventCreate) sqlSave(ctx context.Context) (*VideoProviderCallbackEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VideoProviderCallbackEventCreate) createSpec() (*VideoProviderCallbackEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &VideoProviderCallbackEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(videoprovidercallbackevent.Table, sqlgraph.NewFieldSpec(videoprovidercallbackevent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(videoprovidercallbackevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(videoprovidercallbackevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ProviderCode(); ok {
		_spec.SetField(videoprovidercallbackevent.FieldProviderCode, field.TypeString, value)
		_node.ProviderCode = value
	}
	if value, ok := _c.mutation.ModelAccountID(); ok {
		_spec.SetField(videoprovidercallbackevent.FieldModelAccountID, field.TypeInt64, value)
		_node.ModelAccountID = value
	}
	if value, ok := _c.mutation.ProviderEventID(); ok {
		_spec.SetField(videoprovidercallbackevent.FieldProviderEventID, field.TypeString, value)
		_node.ProviderEventID = value
	}
	if value, ok := _c.mutation.ProviderJobID(); ok {
		_spec.SetField(videoprovidercallbackevent.FieldProviderJobID, field.TypeString, value)
		_node.ProviderJobID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(videoprovidercallbackevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PayloadSnapshot(); ok {
		_spec.SetField(videoprovidercallbackevent.FieldPayloadSnapshot, field.TypeJSON, value)
		_node.PayloadSnapshot = value
	}
	if value, ok := _c.mutation.ReceivedAt(); ok {
		_spec.SetField(videoprovidercallbackevent.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = value
	}
	if value, ok := _c.mutation.ProcessedAt(); ok {
		_spec.SetField(videoprovidercallbackevent.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = &value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(videoprovidercallbackevent.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(videoprovidercallbackevent.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	return _node, _spec
}

// VideoProviderCallbackEventCreateBulk is the builder for creating many VideoProviderCallbackEvent entities in bulk.
type VideoProviderCallbackEventCreateBulk struct {
	config
	err      error
	builders []*VideoProviderCallbackEventCreate
}

// Save creates the VideoProviderCallbackEvent entities in the database.
func (_c *VideoProviderCallbackEventCreateBulk) Save(ctx context.Context) ([]*VideoProviderCallbackEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VideoProviderCallbackEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VideoProviderCallbackEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VideoProviderCallbackEventCreateBulk) SaveX(ctx context.Context) []*VideoProviderCallbackEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoProviderCallbackEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoProviderCallbackEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
