// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/videomodelratecard"
)

// VideoModelRateCard is the model entity for the VideoModelRateCard schema.
type VideoModelRateCard struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// AccountModelID holds the value of the "account_model_id" field.
	AccountModelID int64 `json:"account_model_id,omitempty"`
	// ProviderCode holds the value of the "provider_code" field.
	ProviderCode string `json:"provider_code,omitempty"`
	// PricingSchema holds the value of the "pricing_schema" field.
	PricingSchema string `json:"pricing_schema,omitempty"`
	// RateVersion holds the value of the "rate_version" field.
	RateVersion int `json:"rate_version,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// RateConfig holds the value of the "rate_config" field.
	RateConfig map[string]interface{} `json:"rate_config,omitempty"`
	// SourceReference holds the value of the "source_reference" field.
	SourceReference string `json:"source_reference,omitempty"`
	// EffectiveAt holds the value of the "effective_at" field.
	EffectiveAt time.Time `json:"effective_at,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled      bool `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VideoModelRateCard) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case videomodelratecard.FieldRateConfig:
			values[i] = new([]byte)
		case videomodelratecard.FieldEnabled:
			values[i] = new(sql.NullBool)
		case videomodelratecard.FieldID, videomodelratecard.FieldAccountModelID, videomodelratecard.FieldRateVersion:
			values[i] = new(sql.NullInt64)
		case videomodelratecard.FieldProviderCode, videomodelratecard.FieldPricingSchema, videomodelratecard.FieldCurrency, videomodelratecard.FieldSourceReference:
			values[i] = new(sql.NullString)
		case videomodelratecard.FieldCreatedAt, videomodelratecard.FieldUpdatedAt, videomodelratecard.FieldDeletedAt, videomodelratecard.FieldEffectiveAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VideoModelRateCard fields.
func (_m *VideoModelRateCard) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case videomodelratecard.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case videomodelratecard.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case videomodelratecard.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case videomodelratecard.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case videomodelratecard.FieldAccountModelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_model_id", values[i])
			} else if value.Valid {
				_m.AccountModelID = value.Int64
			}
		case videomodelratecard.FieldProviderCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_code", values[i])
			} else if value.Valid {
				_m.ProviderCode = value.String
			}
		case videomodelratecard.FieldPricingSchema:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pricing_schema", values[i])
			} else if value.Valid {
				_m.PricingSchema = value.String
			}
		case videomodelratecard.FieldRateVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_version", values[i])
			} else if value.Valid {
				_m.RateVersion = int(value.Int64)
			}
		case videomodelratecard.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case videomodelratecard.FieldRateConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field rate_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RateConfig); err != nil {
					return fmt.Errorf("unmarshal field rate_config: %w", err)
				}
			}
		case videomodelratecard.FieldSourceReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_reference", values[i])
			} else if value.Valid {
				_m.SourceReference = value.String
			}
		case videomodelratecard.FieldEffectiveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_at", values[i])
			} else if value.Valid {
				_m.EffectiveAt = value.Time
			}
		case videomodelratecard.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VideoModelRateCard.
// This includes values selected through modifiers, order, etc.
func (_m *VideoModelRateCard) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this VideoModelRateCard.
// Note that you need to call VideoModelRateCard.Unwrap() before calling this method if this VideoModelRateCard
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VideoModelRateCard) Update() *VideoModelRateCardUpdateOne {
	return NewVideoModelRateCardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VideoModelRateCard entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VideoModelRateCard) Unwrap() *VideoModelRateCard {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VideoModelRateCard is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VideoModelRateCard) String() string {
	var builder strings.Builder
	builder.WriteString("VideoModelRateCard(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("account_model_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountModelID))
	builder.WriteString(", ")
	builder.WriteString("provider_code=")
	builder.WriteString(_m.ProviderCode)
	builder.WriteString(", ")
	builder.WriteString("pricing_schema=")
	builder.WriteString(_m.PricingSchema)
	builder.WriteString(", ")
	builder.WriteString("rate_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateVersion))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("rate_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateConfig))
	builder.WriteString(", ")
	builder.WriteString("source_reference=")
	builder.WriteString(_m.SourceReference)
	builder.WriteString(", ")
	builder.WriteString("effective_at=")
	builder.WriteString(_m.EffectiveAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// VideoModelRateCards is a parsable slice of VideoModelRateCard.
type VideoModelRateCards []*VideoModelRateCard
