// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/predicate"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/videotask"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/videotaskattempt"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/videotaskitem"
	"github.com/google/uuid"
)

// VideoTaskItemQuery is the builder for querying VideoTaskItem entities.
type VideoTaskItemQuery struct {
	config
	ctx          *QueryContext
	order        []videotaskitem.OrderOption
	inters       []Interceptor
	predicates   []predicate.VideoTaskItem
	withTask     *VideoTaskQuery
	withAttempts *VideoTaskAttemptQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VideoTaskItemQuery builder.
func (_q *VideoTaskItemQuery) Where(ps ...predicate.VideoTaskItem) *VideoTaskItemQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *VideoTaskItemQuery) Limit(limit int) *VideoTaskItemQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *VideoTaskItemQuery) Offset(offset int) *VideoTaskItemQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *VideoTaskItemQuery) Unique(unique bool) *VideoTaskItemQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *VideoTaskItemQuery) Order(o ...videotaskitem.OrderOption) *VideoTaskItemQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTask chains the current query on the "task" edge.
func (_q *VideoTaskItemQuery) QueryTask() *VideoTaskQuery {
	query := (&VideoTaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(videotaskitem.Table, videotaskitem.FieldID, selector),
			sqlgraph.To(videotask.Table, videotask.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, videotaskitem.TaskTable, videotaskitem.TaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAttempts chains the current query on the "attempts" edge.
func (_q *VideoTaskItemQuery) QueryAttempts() *VideoTaskAttemptQuery {
	query := (&VideoTaskAttemptClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(videotaskitem.Table, videotaskitem.FieldID, selector),
			sqlgraph.To(videotaskattempt.Table, videotaskattempt.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, videotaskitem.AttemptsTable, videotaskitem.AttemptsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VideoTaskItem entity from the query.
// Returns a *NotFoundError when no VideoTaskItem was found.
func (_q *VideoTaskItemQuery) First(ctx context.Context) (*VideoTaskItem, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{videotaskitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *VideoTaskItemQuery) FirstX(ctx context.Context) *VideoTaskItem {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VideoTaskItem ID from the query.
// Returns a *NotFoundError when no VideoTaskItem ID was found.
func (_q *VideoTaskItemQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{videotaskitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *VideoTaskItemQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VideoTaskItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VideoTaskItem entity is found.
// Returns a *NotFoundError when no VideoTaskItem entities are found.
func (_q *VideoTaskItemQuery) Only(ctx context.Context) (*VideoTaskItem, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{videotaskitem.Label}
	default:
		return nil, &NotSingularError{videotaskitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *VideoTaskItemQuery) OnlyX(ctx context.Context) *VideoTaskItem {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VideoTaskItem ID in the query.
// Returns a *NotSingularError when more than one VideoTaskItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *VideoTaskItemQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{videotaskitem.Label}
	default:
		err = &NotSingularError{videotaskitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *VideoTaskItemQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VideoTaskItems.
func (_q *VideoTaskItemQuery) All(ctx context.Context) ([]*VideoTaskItem, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VideoTaskItem, *VideoTaskItemQuery]()
	return withInterceptors[[]*VideoTaskItem](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *VideoTaskItemQuery) AllX(ctx context.Context) []*VideoTaskItem {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VideoTaskItem IDs.
func (_q *VideoTaskItemQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(videotaskitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *VideoTaskItemQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *VideoTaskItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*VideoTaskItemQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *VideoTaskItemQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *VideoTaskItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *VideoTaskItemQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VideoTaskItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *VideoTaskItemQuery) Clone() *VideoTaskItemQuery {
	if _q == nil {
		return nil
	}
	return &VideoTaskItemQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]videotaskitem.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.VideoTaskItem{}, _q.predicates...),
		withTask:     _q.withTask.Clone(),
		withAttempts: _q.withAttempts.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTask tells the query-builder to eager-load the nodes that are connected to
// the "task" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VideoTaskItemQuery) WithTask(opts ...func(*VideoTaskQuery)) *VideoTaskItemQuery {
	query := (&VideoTaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTask = query
	return _q
}

// WithAttempts tells the query-builder to eager-load the nodes that are connected to
// the "attempts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VideoTaskItemQuery) WithAttempts(opts ...func(*VideoTaskAttemptQuery)) *VideoTaskItemQuery {
	query := (&VideoTaskAttemptClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAttempts = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VideoTaskItem.Query().
//		GroupBy(videotaskitem.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *VideoTaskItemQuery) GroupBy(field string, fields ...string) *VideoTaskItemGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VideoTaskItemGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = videotaskitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.VideoTaskItem.Query().
//		Select(videotaskitem.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *VideoTaskItemQuery) Select(fields ...string) *VideoTaskItemSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &VideoTaskItemSelect{VideoTaskItemQuery: _q}
	sbuild.label = videotaskitem.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VideoTaskItemSelect configured with the given aggregations.
func (_q *VideoTaskItemQuery) Aggregate(fns ...AggregateFunc) *VideoTaskItemSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *VideoTaskItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !videotaskitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *VideoTaskItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VideoTaskItem, error) {
	var (
		nodes       = []*VideoTaskItem{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withTask != nil,
			_q.withAttempts != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VideoTaskItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VideoTaskItem{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTask; query != nil {
		if err := _q.loadTask(ctx, query, nodes, nil,
			func(n *VideoTaskItem, e *VideoTask) { n.Edges.Task = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAttempts; query != nil {
		if err := _q.loadAttempts(ctx, query, nodes,
			func(n *VideoTaskItem) { n.Edges.Attempts = []*VideoTaskAttempt{} },
			func(n *VideoTaskItem, e *VideoTaskAttempt) { n.Edges.Attempts = append(n.Edges.Attempts, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *VideoTaskItemQuery) loadTask(ctx context.Context, query *VideoTaskQuery, nodes []*VideoTaskItem, init func(*VideoTaskItem), assign func(*VideoTaskItem, *VideoTask)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*VideoTaskItem)
	for i := range nodes {
		fk := nodes[i].TaskID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(videotask.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *VideoTaskItemQuery) loadAttempts(ctx context.Context, query *VideoTaskAttemptQuery, nodes []*VideoTaskItem, init func(*VideoTaskItem), assign func(*VideoTaskItem, *VideoTaskAttempt)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*VideoTaskItem)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(videotaskattempt.FieldItemID)
	}
	query.Where(predicate.VideoTaskAttempt(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(videotaskitem.AttemptsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ItemID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "item_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *VideoTaskItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *VideoTaskItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(videotaskitem.Table, videotaskitem.Columns, sqlgraph.NewFieldSpec(videotaskitem.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, videotaskitem.FieldID)
		for i := range fields {
			if fields[i] != videotaskitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTask != nil {
			_spec.Node.AddColumnOnce(videotaskitem.FieldTaskID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *VideoTaskItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(videotaskitem.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = videotaskitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VideoTaskItemGroupBy is the group-by builder for VideoTaskItem entities.
type VideoTaskItemGroupBy struct {
	selector
	build *VideoTaskItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *VideoTaskItemGroupBy) Aggregate(fns ...AggregateFunc) *VideoTaskItemGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *VideoTaskItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VideoTaskItemQuery, *VideoTaskItemGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *VideoTaskItemGroupBy) sqlScan(ctx context.Context, root *VideoTaskItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VideoTaskItemSelect is the builder for selecting fields of VideoTaskItem entities.
type VideoTaskItemSelect struct {
	*VideoTaskItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *VideoTaskItemSelect) Aggregate(fns ...AggregateFunc) *VideoTaskItemSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *VideoTaskItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VideoTaskItemQuery, *VideoTaskItemSelect](ctx, _s.VideoTaskItemQuery, _s, _s.inters, v)
}

func (_s *VideoTaskItemSelect) sqlScan(ctx context.Context, root *VideoTaskItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
