// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/videoprovidercallbackevent"
	"github.com/google/uuid"
)

// VideoProviderCallbackEvent is the model entity for the VideoProviderCallbackEvent schema.
type VideoProviderCallbackEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProviderCode holds the value of the "provider_code" field.
	ProviderCode string `json:"provider_code,omitempty"`
	// ModelAccountID holds the value of the "model_account_id" field.
	ModelAccountID int64 `json:"model_account_id,omitempty"`
	// ProviderEventID holds the value of the "provider_event_id" field.
	ProviderEventID string `json:"provider_event_id,omitempty"`
	// ProviderJobID holds the value of the "provider_job_id" field.
	ProviderJobID string `json:"provider_job_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// PayloadSnapshot holds the value of the "payload_snapshot" field.
	PayloadSnapshot map[string]interface{} `json:"payload_snapshot,omitempty"`
	// ReceivedAt holds the value of the "received_at" field.
	ReceivedAt time.Time `json:"received_at,omitempty"`
	// ProcessedAt holds the value of the "processed_at" field.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VideoProviderCallbackEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case videoprovidercallbackevent.FieldPayloadSnapshot:
			values[i] = new([]byte)
		case videoprovidercallbackevent.FieldModelAccountID:
			values[i] = new(sql.NullInt64)
		case videoprovidercallbackevent.FieldProviderCode, videoprovidercallbackevent.FieldProviderEventID, videoprovidercallbackevent.FieldProviderJobID, videoprovidercallbackevent.FieldStatus, videoprovidercallbackevent.FieldErrorCode, videoprovidercallbackevent.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case videoprovidercallbackevent.FieldCreatedAt, videoprovidercallbackevent.FieldUpdatedAt, videoprovidercallbackevent.FieldReceivedAt, videoprovidercallbackevent.FieldProcessedAt:
			values[i] = new(sql.NullTime)
		case videoprovidercallbackevent.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VideoProviderCallbackEvent fields.
func (_m *VideoProviderCallbackEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case videoprovidercallbackevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case videoprovidercallbackevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case videoprovidercallbackevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case videoprovidercallbackevent.FieldProviderCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_code", values[i])
			} else if value.Valid {
				_m.ProviderCode = value.String
			}
		case videoprovidercallbackevent.FieldModelAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_account_id", values[i])
			} else if value.Valid {
				_m.ModelAccountID = value.Int64
			}
		case videoprovidercallbackevent.FieldProviderEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_event_id", values[i])
			} else if value.Valid {
				_m.ProviderEventID = value.String
			}
		case videoprovidercallbackevent.FieldProviderJobID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_job_id", values[i])
			} else if value.Valid {
				_m.ProviderJobID = value.String
			}
		case videoprovidercallbackevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case videoprovidercallbackevent.FieldPayloadSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PayloadSnapshot); err != nil {
					return fmt.Errorf("unmarshal field payload_snapshot: %w", err)
				}
			}
		case videoprovidercallbackevent.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				_m.ReceivedAt = value.Time
			}
		case videoprovidercallbackevent.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				_m.ProcessedAt = new(time.Time)
				*_m.ProcessedAt = value.Time
			}
		case videoprovidercallbackevent.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case videoprovidercallbackevent.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VideoProviderCallbackEvent.
// This includes values selected through modifiers, order, etc.
func (_m *VideoProviderCallbackEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this VideoProviderCallbackEvent.
// Note that you need to call VideoProviderCallbackEvent.Unwrap() before calling this method if this VideoProviderCallbackEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VideoProviderCallbackEvent) Update() *VideoProviderCallbackEventUpdateOne {
	return NewVideoProviderCallbackEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VideoProviderCallbackEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VideoProviderCallbackEvent) Unwrap() *VideoProviderCallbackEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VideoProviderCallbackEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VideoProviderCallbackEvent) String() string {
	var builder strings.Builder
	builder.WriteString("VideoProviderCallbackEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("provider_code=")
	builder.WriteString(_m.ProviderCode)
	builder.WriteString(", ")
	builder.WriteString("model_account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelAccountID))
	builder.WriteString(", ")
	builder.WriteString("provider_event_id=")
	builder.WriteString(_m.ProviderEventID)
	builder.WriteString(", ")
	builder.WriteString("provider_job_id=")
	builder.WriteString(_m.ProviderJobID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("payload_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.PayloadSnapshot))
	builder.WriteString(", ")
	builder.WriteString("received_at=")
	builder.WriteString(_m.ReceivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ProcessedAt; v != nil {
		builder.WriteString("processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// VideoProviderCallbackEvents is a parsable slice of VideoProviderCallbackEvent.
type VideoProviderCallbackEvents []*VideoProviderCallbackEvent
