// Code generated by ent, DO NOT EDIT.

package paymentproviderinstance

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentproviderinstance type in the database.
	Label = "payment_provider_instance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldProviderType holds the string denoting the provider_type field in the database.
	FieldProviderType = "provider_type"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldConfigEncrypted holds the string denoting the config_encrypted field in the database.
	FieldConfigEncrypted = "config_encrypted"
	// FieldCredentialsFingerprint holds the string denoting the credentials_fingerprint field in the database.
	FieldCredentialsFingerprint = "credentials_fingerprint"
	// FieldSupportedMethods holds the string denoting the supported_methods field in the database.
	FieldSupportedMethods = "supported_methods"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldSchedulerWeight holds the string denoting the scheduler_weight field in the database.
	FieldSchedulerWeight = "scheduler_weight"
	// FieldLimits holds the string denoting the limits field in the database.
	FieldLimits = "limits"
	// FieldRefundEnabled holds the string denoting the refund_enabled field in the database.
	FieldRefundEnabled = "refund_enabled"
	// FieldHealthStatus holds the string denoting the health_status field in the database.
	FieldHealthStatus = "health_status"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldLastUsedAt holds the string denoting the last_used_at field in the database.
	FieldLastUsedAt = "last_used_at"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// Table holds the table name of the paymentproviderinstance in the database.
	Table = "payment_provider_instances"
)

// Columns holds all SQL columns for paymentproviderinstance fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldProviderType,
	FieldName,
	FieldConfigEncrypted,
	FieldCredentialsFingerprint,
	FieldSupportedMethods,
	FieldEnabled,
	FieldSortOrder,
	FieldSchedulerWeight,
	FieldLimits,
	FieldRefundEnabled,
	FieldHealthStatus,
	FieldLastError,
	FieldLastUsedAt,
	FieldMetadata,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ProviderTypeValidator is a validator for the "provider_type" field. It is called by the builders before save.
	ProviderTypeValidator func(string) error
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCredentialsFingerprint holds the default value on creation for the "credentials_fingerprint" field.
	DefaultCredentialsFingerprint string
	// CredentialsFingerprintValidator is a validator for the "credentials_fingerprint" field. It is called by the builders before save.
	CredentialsFingerprintValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultSchedulerWeight holds the default value on creation for the "scheduler_weight" field.
	DefaultSchedulerWeight int
	// DefaultRefundEnabled holds the default value on creation for the "refund_enabled" field.
	DefaultRefundEnabled bool
	// DefaultHealthStatus holds the default value on creation for the "health_status" field.
	DefaultHealthStatus string
	// HealthStatusValidator is a validator for the "health_status" field. It is called by the builders before save.
	HealthStatusValidator func(string) error
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// LastErrorValidator is a validator for the "last_error" field. It is called by the builders before save.
	LastErrorValidator func(string) error
)

// OrderOption defines the ordering options for the PaymentProviderInstance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProviderType orders the results by the provider_type field.
func ByProviderType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderType, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCredentialsFingerprint orders the results by the credentials_fingerprint field.
func ByCredentialsFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialsFingerprint, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// BySchedulerWeight orders the results by the scheduler_weight field.
func BySchedulerWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchedulerWeight, opts...).ToFunc()
}

// ByRefundEnabled orders the results by the refund_enabled field.
func ByRefundEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundEnabled, opts...).ToFunc()
}

// ByHealthStatus orders the results by the health_status field.
func ByHealthStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHealthStatus, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByLastUsedAt orders the results by the last_used_at field.
func ByLastUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedAt, opts...).ToFunc()
}
