// Code generated by ent, DO NOT EDIT.

package storageconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldName, v))
}

// Driver applies equality check predicate on the "driver" field. It's identical to DriverEQ.
func Driver(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldDriver, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldEndpoint, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldRegion, v))
}

// Bucket applies equality check predicate on the "bucket" field. It's identical to BucketEQ.
func Bucket(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldBucket, v))
}

// Prefix applies equality check predicate on the "prefix" field. It's identical to PrefixEQ.
func Prefix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldPrefix, v))
}

// ForcePathStyle applies equality check predicate on the "force_path_style" field. It's identical to ForcePathStyleEQ.
func ForcePathStyle(v bool) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldForcePathStyle, v))
}

// AccessKeyIDEncrypted applies equality check predicate on the "access_key_id_encrypted" field. It's identical to AccessKeyIDEncryptedEQ.
func AccessKeyIDEncrypted(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldAccessKeyIDEncrypted, v))
}

// SecretAccessKeyEncrypted applies equality check predicate on the "secret_access_key_encrypted" field. It's identical to SecretAccessKeyEncryptedEQ.
func SecretAccessKeyEncrypted(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldSecretAccessKeyEncrypted, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldStatus, v))
}

// IsDefaultWrite applies equality check predicate on the "is_default_write" field. It's identical to IsDefaultWriteEQ.
func IsDefaultWrite(v bool) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldIsDefaultWrite, v))
}

// LastTestStatus applies equality check predicate on the "last_test_status" field. It's identical to LastTestStatusEQ.
func LastTestStatus(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldLastTestStatus, v))
}

// LastTestError applies equality check predicate on the "last_test_error" field. It's identical to LastTestErrorEQ.
func LastTestError(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldLastTestError, v))
}

// LastTestedAt applies equality check predicate on the "last_tested_at" field. It's identical to LastTestedAtEQ.
func LastTestedAt(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldLastTestedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContainsFold(FieldName, v))
}

// DriverEQ applies the EQ predicate on the "driver" field.
func DriverEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldDriver, v))
}

// DriverNEQ applies the NEQ predicate on the "driver" field.
func DriverNEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldDriver, v))
}

// DriverIn applies the In predicate on the "driver" field.
func DriverIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldDriver, vs...))
}

// DriverNotIn applies the NotIn predicate on the "driver" field.
func DriverNotIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldDriver, vs...))
}

// DriverGT applies the GT predicate on the "driver" field.
func DriverGT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldDriver, v))
}

// DriverGTE applies the GTE predicate on the "driver" field.
func DriverGTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldDriver, v))
}

// DriverLT applies the LT predicate on the "driver" field.
func DriverLT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldDriver, v))
}

// DriverLTE applies the LTE predicate on the "driver" field.
func DriverLTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldDriver, v))
}

// DriverContains applies the Contains predicate on the "driver" field.
func DriverContains(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContains(FieldDriver, v))
}

// DriverHasPrefix applies the HasPrefix predicate on the "driver" field.
func DriverHasPrefix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasPrefix(FieldDriver, v))
}

// DriverHasSuffix applies the HasSuffix predicate on the "driver" field.
func DriverHasSuffix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasSuffix(FieldDriver, v))
}

// DriverEqualFold applies the EqualFold predicate on the "driver" field.
func DriverEqualFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEqualFold(FieldDriver, v))
}

// DriverContainsFold applies the ContainsFold predicate on the "driver" field.
func DriverContainsFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContainsFold(FieldDriver, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContainsFold(FieldEndpoint, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContainsFold(FieldRegion, v))
}

// BucketEQ applies the EQ predicate on the "bucket" field.
func BucketEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldBucket, v))
}

// BucketNEQ applies the NEQ predicate on the "bucket" field.
func BucketNEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldBucket, v))
}

// BucketIn applies the In predicate on the "bucket" field.
func BucketIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldBucket, vs...))
}

// BucketNotIn applies the NotIn predicate on the "bucket" field.
func BucketNotIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldBucket, vs...))
}

// BucketGT applies the GT predicate on the "bucket" field.
func BucketGT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldBucket, v))
}

// BucketGTE applies the GTE predicate on the "bucket" field.
func BucketGTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldBucket, v))
}

// BucketLT applies the LT predicate on the "bucket" field.
func BucketLT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldBucket, v))
}

// BucketLTE applies the LTE predicate on the "bucket" field.
func BucketLTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldBucket, v))
}

// BucketContains applies the Contains predicate on the "bucket" field.
func BucketContains(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContains(FieldBucket, v))
}

// BucketHasPrefix applies the HasPrefix predicate on the "bucket" field.
func BucketHasPrefix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasPrefix(FieldBucket, v))
}

// BucketHasSuffix applies the HasSuffix predicate on the "bucket" field.
func BucketHasSuffix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasSuffix(FieldBucket, v))
}

// BucketEqualFold applies the EqualFold predicate on the "bucket" field.
func BucketEqualFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEqualFold(FieldBucket, v))
}

// BucketContainsFold applies the ContainsFold predicate on the "bucket" field.
func BucketContainsFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContainsFold(FieldBucket, v))
}

// PrefixEQ applies the EQ predicate on the "prefix" field.
func PrefixEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldPrefix, v))
}

// PrefixNEQ applies the NEQ predicate on the "prefix" field.
func PrefixNEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldPrefix, v))
}

// PrefixIn applies the In predicate on the "prefix" field.
func PrefixIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldPrefix, vs...))
}

// PrefixNotIn applies the NotIn predicate on the "prefix" field.
func PrefixNotIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldPrefix, vs...))
}

// PrefixGT applies the GT predicate on the "prefix" field.
func PrefixGT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldPrefix, v))
}

// PrefixGTE applies the GTE predicate on the "prefix" field.
func PrefixGTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldPrefix, v))
}

// PrefixLT applies the LT predicate on the "prefix" field.
func PrefixLT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldPrefix, v))
}

// PrefixLTE applies the LTE predicate on the "prefix" field.
func PrefixLTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldPrefix, v))
}

// PrefixContains applies the Contains predicate on the "prefix" field.
func PrefixContains(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContains(FieldPrefix, v))
}

// PrefixHasPrefix applies the HasPrefix predicate on the "prefix" field.
func PrefixHasPrefix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasPrefix(FieldPrefix, v))
}

// PrefixHasSuffix applies the HasSuffix predicate on the "prefix" field.
func PrefixHasSuffix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasSuffix(FieldPrefix, v))
}

// PrefixEqualFold applies the EqualFold predicate on the "prefix" field.
func PrefixEqualFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEqualFold(FieldPrefix, v))
}

// PrefixContainsFold applies the ContainsFold predicate on the "prefix" field.
func PrefixContainsFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContainsFold(FieldPrefix, v))
}

// ForcePathStyleEQ applies the EQ predicate on the "force_path_style" field.
func ForcePathStyleEQ(v bool) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldForcePathStyle, v))
}

// ForcePathStyleNEQ applies the NEQ predicate on the "force_path_style" field.
func ForcePathStyleNEQ(v bool) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldForcePathStyle, v))
}

// AccessKeyIDEncryptedEQ applies the EQ predicate on the "access_key_id_encrypted" field.
func AccessKeyIDEncryptedEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldAccessKeyIDEncrypted, v))
}

// AccessKeyIDEncryptedNEQ applies the NEQ predicate on the "access_key_id_encrypted" field.
func AccessKeyIDEncryptedNEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldAccessKeyIDEncrypted, v))
}

// AccessKeyIDEncryptedIn applies the In predicate on the "access_key_id_encrypted" field.
func AccessKeyIDEncryptedIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldAccessKeyIDEncrypted, vs...))
}

// AccessKeyIDEncryptedNotIn applies the NotIn predicate on the "access_key_id_encrypted" field.
func AccessKeyIDEncryptedNotIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldAccessKeyIDEncrypted, vs...))
}

// AccessKeyIDEncryptedGT applies the GT predicate on the "access_key_id_encrypted" field.
func AccessKeyIDEncryptedGT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldAccessKeyIDEncrypted, v))
}

// AccessKeyIDEncryptedGTE applies the GTE predicate on the "access_key_id_encrypted" field.
func AccessKeyIDEncryptedGTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldAccessKeyIDEncrypted, v))
}

// AccessKeyIDEncryptedLT applies the LT predicate on the "access_key_id_encrypted" field.
func AccessKeyIDEncryptedLT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldAccessKeyIDEncrypted, v))
}

// AccessKeyIDEncryptedLTE applies the LTE predicate on the "access_key_id_encrypted" field.
func AccessKeyIDEncryptedLTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldAccessKeyIDEncrypted, v))
}

// AccessKeyIDEncryptedContains applies the Contains predicate on the "access_key_id_encrypted" field.
func AccessKeyIDEncryptedContains(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContains(FieldAccessKeyIDEncrypted, v))
}

// AccessKeyIDEncryptedHasPrefix applies the HasPrefix predicate on the "access_key_id_encrypted" field.
func AccessKeyIDEncryptedHasPrefix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasPrefix(FieldAccessKeyIDEncrypted, v))
}

// AccessKeyIDEncryptedHasSuffix applies the HasSuffix predicate on the "access_key_id_encrypted" field.
func AccessKeyIDEncryptedHasSuffix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasSuffix(FieldAccessKeyIDEncrypted, v))
}

// AccessKeyIDEncryptedEqualFold applies the EqualFold predicate on the "access_key_id_encrypted" field.
func AccessKeyIDEncryptedEqualFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEqualFold(FieldAccessKeyIDEncrypted, v))
}

// AccessKeyIDEncryptedContainsFold applies the ContainsFold predicate on the "access_key_id_encrypted" field.
func AccessKeyIDEncryptedContainsFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContainsFold(FieldAccessKeyIDEncrypted, v))
}

// SecretAccessKeyEncryptedEQ applies the EQ predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedNEQ applies the NEQ predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedNEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedIn applies the In predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldSecretAccessKeyEncrypted, vs...))
}

// SecretAccessKeyEncryptedNotIn applies the NotIn predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedNotIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldSecretAccessKeyEncrypted, vs...))
}

// SecretAccessKeyEncryptedGT applies the GT predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedGT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedGTE applies the GTE predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedGTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedLT applies the LT predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedLT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedLTE applies the LTE predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedLTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedContains applies the Contains predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedContains(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContains(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedHasPrefix applies the HasPrefix predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedHasPrefix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasPrefix(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedHasSuffix applies the HasSuffix predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedHasSuffix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasSuffix(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedEqualFold applies the EqualFold predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedEqualFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEqualFold(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedContainsFold applies the ContainsFold predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedContainsFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContainsFold(FieldSecretAccessKeyEncrypted, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContainsFold(FieldStatus, v))
}

// IsDefaultWriteEQ applies the EQ predicate on the "is_default_write" field.
func IsDefaultWriteEQ(v bool) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldIsDefaultWrite, v))
}

// IsDefaultWriteNEQ applies the NEQ predicate on the "is_default_write" field.
func IsDefaultWriteNEQ(v bool) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldIsDefaultWrite, v))
}

// LastTestStatusEQ applies the EQ predicate on the "last_test_status" field.
func LastTestStatusEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldLastTestStatus, v))
}

// LastTestStatusNEQ applies the NEQ predicate on the "last_test_status" field.
func LastTestStatusNEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldLastTestStatus, v))
}

// LastTestStatusIn applies the In predicate on the "last_test_status" field.
func LastTestStatusIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldLastTestStatus, vs...))
}

// LastTestStatusNotIn applies the NotIn predicate on the "last_test_status" field.
func LastTestStatusNotIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldLastTestStatus, vs...))
}

// LastTestStatusGT applies the GT predicate on the "last_test_status" field.
func LastTestStatusGT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldLastTestStatus, v))
}

// LastTestStatusGTE applies the GTE predicate on the "last_test_status" field.
func LastTestStatusGTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldLastTestStatus, v))
}

// LastTestStatusLT applies the LT predicate on the "last_test_status" field.
func LastTestStatusLT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldLastTestStatus, v))
}

// LastTestStatusLTE applies the LTE predicate on the "last_test_status" field.
func LastTestStatusLTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldLastTestStatus, v))
}

// LastTestStatusContains applies the Contains predicate on the "last_test_status" field.
func LastTestStatusContains(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContains(FieldLastTestStatus, v))
}

// LastTestStatusHasPrefix applies the HasPrefix predicate on the "last_test_status" field.
func LastTestStatusHasPrefix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasPrefix(FieldLastTestStatus, v))
}

// LastTestStatusHasSuffix applies the HasSuffix predicate on the "last_test_status" field.
func LastTestStatusHasSuffix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasSuffix(FieldLastTestStatus, v))
}

// LastTestStatusEqualFold applies the EqualFold predicate on the "last_test_status" field.
func LastTestStatusEqualFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEqualFold(FieldLastTestStatus, v))
}

// LastTestStatusContainsFold applies the ContainsFold predicate on the "last_test_status" field.
func LastTestStatusContainsFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContainsFold(FieldLastTestStatus, v))
}

// LastTestErrorEQ applies the EQ predicate on the "last_test_error" field.
func LastTestErrorEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldLastTestError, v))
}

// LastTestErrorNEQ applies the NEQ predicate on the "last_test_error" field.
func LastTestErrorNEQ(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldLastTestError, v))
}

// LastTestErrorIn applies the In predicate on the "last_test_error" field.
func LastTestErrorIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldLastTestError, vs...))
}

// LastTestErrorNotIn applies the NotIn predicate on the "last_test_error" field.
func LastTestErrorNotIn(vs ...string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldLastTestError, vs...))
}

// LastTestErrorGT applies the GT predicate on the "last_test_error" field.
func LastTestErrorGT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldLastTestError, v))
}

// LastTestErrorGTE applies the GTE predicate on the "last_test_error" field.
func LastTestErrorGTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldLastTestError, v))
}

// LastTestErrorLT applies the LT predicate on the "last_test_error" field.
func LastTestErrorLT(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldLastTestError, v))
}

// LastTestErrorLTE applies the LTE predicate on the "last_test_error" field.
func LastTestErrorLTE(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldLastTestError, v))
}

// LastTestErrorContains applies the Contains predicate on the "last_test_error" field.
func LastTestErrorContains(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContains(FieldLastTestError, v))
}

// LastTestErrorHasPrefix applies the HasPrefix predicate on the "last_test_error" field.
func LastTestErrorHasPrefix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasPrefix(FieldLastTestError, v))
}

// LastTestErrorHasSuffix applies the HasSuffix predicate on the "last_test_error" field.
func LastTestErrorHasSuffix(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldHasSuffix(FieldLastTestError, v))
}

// LastTestErrorEqualFold applies the EqualFold predicate on the "last_test_error" field.
func LastTestErrorEqualFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEqualFold(FieldLastTestError, v))
}

// LastTestErrorContainsFold applies the ContainsFold predicate on the "last_test_error" field.
func LastTestErrorContainsFold(v string) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldContainsFold(FieldLastTestError, v))
}

// LastTestedAtEQ applies the EQ predicate on the "last_tested_at" field.
func LastTestedAtEQ(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldEQ(FieldLastTestedAt, v))
}

// LastTestedAtNEQ applies the NEQ predicate on the "last_tested_at" field.
func LastTestedAtNEQ(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNEQ(FieldLastTestedAt, v))
}

// LastTestedAtIn applies the In predicate on the "last_tested_at" field.
func LastTestedAtIn(vs ...time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIn(FieldLastTestedAt, vs...))
}

// LastTestedAtNotIn applies the NotIn predicate on the "last_tested_at" field.
func LastTestedAtNotIn(vs ...time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotIn(FieldLastTestedAt, vs...))
}

// LastTestedAtGT applies the GT predicate on the "last_tested_at" field.
func LastTestedAtGT(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGT(FieldLastTestedAt, v))
}

// LastTestedAtGTE applies the GTE predicate on the "last_tested_at" field.
func LastTestedAtGTE(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldGTE(FieldLastTestedAt, v))
}

// LastTestedAtLT applies the LT predicate on the "last_tested_at" field.
func LastTestedAtLT(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLT(FieldLastTestedAt, v))
}

// LastTestedAtLTE applies the LTE predicate on the "last_tested_at" field.
func LastTestedAtLTE(v time.Time) predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldLTE(FieldLastTestedAt, v))
}

// LastTestedAtIsNil applies the IsNil predicate on the "last_tested_at" field.
func LastTestedAtIsNil() predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldIsNull(FieldLastTestedAt))
}

// LastTestedAtNotNil applies the NotNil predicate on the "last_tested_at" field.
func LastTestedAtNotNil() predicate.StorageConfig {
	return predicate.StorageConfig(sql.FieldNotNull(FieldLastTestedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StorageConfig) predicate.StorageConfig {
	return predicate.StorageConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StorageConfig) predicate.StorageConfig {
	return predicate.StorageConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StorageConfig) predicate.StorageConfig {
	return predicate.StorageConfig(sql.NotPredicates(p))
}
