// Code generated by ent, DO NOT EDIT.

package clusternode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldUpdatedAt, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldNodeID, v))
}

// InstallationID applies equality check predicate on the "installation_id" field. It's identical to InstallationIDEQ.
func InstallationID(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldInstallationID, v))
}

// AppVersion applies equality check predicate on the "app_version" field. It's identical to AppVersionEQ.
func AppVersion(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldAppVersion, v))
}

// RuntimeSchemaVersion applies equality check predicate on the "runtime_schema_version" field. It's identical to RuntimeSchemaVersionEQ.
func RuntimeSchemaVersion(v int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldRuntimeSchemaVersion, v))
}

// ConfigRevision applies equality check predicate on the "config_revision" field. It's identical to ConfigRevisionEQ.
func ConfigRevision(v int64) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldConfigRevision, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldLastError, v))
}

// LastHeartbeatAt applies equality check predicate on the "last_heartbeat_at" field. It's identical to LastHeartbeatAtEQ.
func LastHeartbeatAt(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldLastHeartbeatAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLTE(FieldUpdatedAt, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDContains applies the Contains predicate on the "node_id" field.
func NodeIDContains(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldContains(FieldNodeID, v))
}

// NodeIDHasPrefix applies the HasPrefix predicate on the "node_id" field.
func NodeIDHasPrefix(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldHasPrefix(FieldNodeID, v))
}

// NodeIDHasSuffix applies the HasSuffix predicate on the "node_id" field.
func NodeIDHasSuffix(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldHasSuffix(FieldNodeID, v))
}

// NodeIDEqualFold applies the EqualFold predicate on the "node_id" field.
func NodeIDEqualFold(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEqualFold(FieldNodeID, v))
}

// NodeIDContainsFold applies the ContainsFold predicate on the "node_id" field.
func NodeIDContainsFold(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldContainsFold(FieldNodeID, v))
}

// InstallationIDEQ applies the EQ predicate on the "installation_id" field.
func InstallationIDEQ(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldInstallationID, v))
}

// InstallationIDNEQ applies the NEQ predicate on the "installation_id" field.
func InstallationIDNEQ(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNEQ(FieldInstallationID, v))
}

// InstallationIDIn applies the In predicate on the "installation_id" field.
func InstallationIDIn(vs ...string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldIn(FieldInstallationID, vs...))
}

// InstallationIDNotIn applies the NotIn predicate on the "installation_id" field.
func InstallationIDNotIn(vs ...string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNotIn(FieldInstallationID, vs...))
}

// InstallationIDGT applies the GT predicate on the "installation_id" field.
func InstallationIDGT(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGT(FieldInstallationID, v))
}

// InstallationIDGTE applies the GTE predicate on the "installation_id" field.
func InstallationIDGTE(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGTE(FieldInstallationID, v))
}

// InstallationIDLT applies the LT predicate on the "installation_id" field.
func InstallationIDLT(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLT(FieldInstallationID, v))
}

// InstallationIDLTE applies the LTE predicate on the "installation_id" field.
func InstallationIDLTE(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLTE(FieldInstallationID, v))
}

// InstallationIDContains applies the Contains predicate on the "installation_id" field.
func InstallationIDContains(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldContains(FieldInstallationID, v))
}

// InstallationIDHasPrefix applies the HasPrefix predicate on the "installation_id" field.
func InstallationIDHasPrefix(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldHasPrefix(FieldInstallationID, v))
}

// InstallationIDHasSuffix applies the HasSuffix predicate on the "installation_id" field.
func InstallationIDHasSuffix(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldHasSuffix(FieldInstallationID, v))
}

// InstallationIDEqualFold applies the EqualFold predicate on the "installation_id" field.
func InstallationIDEqualFold(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEqualFold(FieldInstallationID, v))
}

// InstallationIDContainsFold applies the ContainsFold predicate on the "installation_id" field.
func InstallationIDContainsFold(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldContainsFold(FieldInstallationID, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNotIn(FieldRole, vs...))
}

// AppVersionEQ applies the EQ predicate on the "app_version" field.
func AppVersionEQ(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldAppVersion, v))
}

// AppVersionNEQ applies the NEQ predicate on the "app_version" field.
func AppVersionNEQ(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNEQ(FieldAppVersion, v))
}

// AppVersionIn applies the In predicate on the "app_version" field.
func AppVersionIn(vs ...string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldIn(FieldAppVersion, vs...))
}

// AppVersionNotIn applies the NotIn predicate on the "app_version" field.
func AppVersionNotIn(vs ...string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNotIn(FieldAppVersion, vs...))
}

// AppVersionGT applies the GT predicate on the "app_version" field.
func AppVersionGT(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGT(FieldAppVersion, v))
}

// AppVersionGTE applies the GTE predicate on the "app_version" field.
func AppVersionGTE(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGTE(FieldAppVersion, v))
}

// AppVersionLT applies the LT predicate on the "app_version" field.
func AppVersionLT(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLT(FieldAppVersion, v))
}

// AppVersionLTE applies the LTE predicate on the "app_version" field.
func AppVersionLTE(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLTE(FieldAppVersion, v))
}

// AppVersionContains applies the Contains predicate on the "app_version" field.
func AppVersionContains(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldContains(FieldAppVersion, v))
}

// AppVersionHasPrefix applies the HasPrefix predicate on the "app_version" field.
func AppVersionHasPrefix(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldHasPrefix(FieldAppVersion, v))
}

// AppVersionHasSuffix applies the HasSuffix predicate on the "app_version" field.
func AppVersionHasSuffix(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldHasSuffix(FieldAppVersion, v))
}

// AppVersionEqualFold applies the EqualFold predicate on the "app_version" field.
func AppVersionEqualFold(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEqualFold(FieldAppVersion, v))
}

// AppVersionContainsFold applies the ContainsFold predicate on the "app_version" field.
func AppVersionContainsFold(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldContainsFold(FieldAppVersion, v))
}

// RuntimeSchemaVersionEQ applies the EQ predicate on the "runtime_schema_version" field.
func RuntimeSchemaVersionEQ(v int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldRuntimeSchemaVersion, v))
}

// RuntimeSchemaVersionNEQ applies the NEQ predicate on the "runtime_schema_version" field.
func RuntimeSchemaVersionNEQ(v int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNEQ(FieldRuntimeSchemaVersion, v))
}

// RuntimeSchemaVersionIn applies the In predicate on the "runtime_schema_version" field.
func RuntimeSchemaVersionIn(vs ...int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldIn(FieldRuntimeSchemaVersion, vs...))
}

// RuntimeSchemaVersionNotIn applies the NotIn predicate on the "runtime_schema_version" field.
func RuntimeSchemaVersionNotIn(vs ...int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNotIn(FieldRuntimeSchemaVersion, vs...))
}

// RuntimeSchemaVersionGT applies the GT predicate on the "runtime_schema_version" field.
func RuntimeSchemaVersionGT(v int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGT(FieldRuntimeSchemaVersion, v))
}

// RuntimeSchemaVersionGTE applies the GTE predicate on the "runtime_schema_version" field.
func RuntimeSchemaVersionGTE(v int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGTE(FieldRuntimeSchemaVersion, v))
}

// RuntimeSchemaVersionLT applies the LT predicate on the "runtime_schema_version" field.
func RuntimeSchemaVersionLT(v int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLT(FieldRuntimeSchemaVersion, v))
}

// RuntimeSchemaVersionLTE applies the LTE predicate on the "runtime_schema_version" field.
func RuntimeSchemaVersionLTE(v int) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLTE(FieldRuntimeSchemaVersion, v))
}

// ConfigRevisionEQ applies the EQ predicate on the "config_revision" field.
func ConfigRevisionEQ(v int64) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldConfigRevision, v))
}

// ConfigRevisionNEQ applies the NEQ predicate on the "config_revision" field.
func ConfigRevisionNEQ(v int64) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNEQ(FieldConfigRevision, v))
}

// ConfigRevisionIn applies the In predicate on the "config_revision" field.
func ConfigRevisionIn(vs ...int64) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldIn(FieldConfigRevision, vs...))
}

// ConfigRevisionNotIn applies the NotIn predicate on the "config_revision" field.
func ConfigRevisionNotIn(vs ...int64) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNotIn(FieldConfigRevision, vs...))
}

// ConfigRevisionGT applies the GT predicate on the "config_revision" field.
func ConfigRevisionGT(v int64) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGT(FieldConfigRevision, v))
}

// ConfigRevisionGTE applies the GTE predicate on the "config_revision" field.
func ConfigRevisionGTE(v int64) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGTE(FieldConfigRevision, v))
}

// ConfigRevisionLT applies the LT predicate on the "config_revision" field.
func ConfigRevisionLT(v int64) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLT(FieldConfigRevision, v))
}

// ConfigRevisionLTE applies the LTE predicate on the "config_revision" field.
func ConfigRevisionLTE(v int64) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLTE(FieldConfigRevision, v))
}

// HealthEQ applies the EQ predicate on the "health" field.
func HealthEQ(v Health) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldHealth, v))
}

// HealthNEQ applies the NEQ predicate on the "health" field.
func HealthNEQ(v Health) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNEQ(FieldHealth, v))
}

// HealthIn applies the In predicate on the "health" field.
func HealthIn(vs ...Health) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldIn(FieldHealth, vs...))
}

// HealthNotIn applies the NotIn predicate on the "health" field.
func HealthNotIn(vs ...Health) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNotIn(FieldHealth, vs...))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldContainsFold(FieldLastError, v))
}

// LastHeartbeatAtEQ applies the EQ predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtEQ(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldEQ(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtNEQ applies the NEQ predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNEQ(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNEQ(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtIn applies the In predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtIn(vs ...time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldIn(FieldLastHeartbeatAt, vs...))
}

// LastHeartbeatAtNotIn applies the NotIn predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNotIn(vs ...time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNotIn(FieldLastHeartbeatAt, vs...))
}

// LastHeartbeatAtGT applies the GT predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtGT(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGT(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtGTE applies the GTE predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtGTE(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldGTE(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtLT applies the LT predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtLT(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLT(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtLTE applies the LTE predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtLTE(v time.Time) predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldLTE(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtIsNil applies the IsNil predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtIsNil() predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldIsNull(FieldLastHeartbeatAt))
}

// LastHeartbeatAtNotNil applies the NotNil predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNotNil() predicate.ClusterNode {
	return predicate.ClusterNode(sql.FieldNotNull(FieldLastHeartbeatAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ClusterNode) predicate.ClusterNode {
	return predicate.ClusterNode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ClusterNode) predicate.ClusterNode {
	return predicate.ClusterNode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ClusterNode) predicate.ClusterNode {
	return predicate.ClusterNode(sql.NotPredicates(p))
}
