// Code generated by ent, DO NOT EDIT.

package modelprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderCode applies equality check predicate on the "provider_code" field. It's identical to ProviderCodeEQ.
func ProviderCode(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldProviderCode, v))
}

// ProviderType applies equality check predicate on the "provider_type" field. It's identical to ProviderTypeEQ.
func ProviderType(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldProviderType, v))
}

// AuthConfigEncrypted applies equality check predicate on the "auth_config_encrypted" field. It's identical to AuthConfigEncryptedEQ.
func AuthConfigEncrypted(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldAuthConfigEncrypted, v))
}

// HealthStatus applies equality check predicate on the "health_status" field. It's identical to HealthStatusEQ.
func HealthStatus(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldHealthStatus, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProviderCodeEQ applies the EQ predicate on the "provider_code" field.
func ProviderCodeEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldProviderCode, v))
}

// ProviderCodeNEQ applies the NEQ predicate on the "provider_code" field.
func ProviderCodeNEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldProviderCode, v))
}

// ProviderCodeIn applies the In predicate on the "provider_code" field.
func ProviderCodeIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldProviderCode, vs...))
}

// ProviderCodeNotIn applies the NotIn predicate on the "provider_code" field.
func ProviderCodeNotIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldProviderCode, vs...))
}

// ProviderCodeGT applies the GT predicate on the "provider_code" field.
func ProviderCodeGT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldProviderCode, v))
}

// ProviderCodeGTE applies the GTE predicate on the "provider_code" field.
func ProviderCodeGTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldProviderCode, v))
}

// ProviderCodeLT applies the LT predicate on the "provider_code" field.
func ProviderCodeLT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldProviderCode, v))
}

// ProviderCodeLTE applies the LTE predicate on the "provider_code" field.
func ProviderCodeLTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldProviderCode, v))
}

// ProviderCodeContains applies the Contains predicate on the "provider_code" field.
func ProviderCodeContains(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContains(FieldProviderCode, v))
}

// ProviderCodeHasPrefix applies the HasPrefix predicate on the "provider_code" field.
func ProviderCodeHasPrefix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasPrefix(FieldProviderCode, v))
}

// ProviderCodeHasSuffix applies the HasSuffix predicate on the "provider_code" field.
func ProviderCodeHasSuffix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasSuffix(FieldProviderCode, v))
}

// ProviderCodeEqualFold applies the EqualFold predicate on the "provider_code" field.
func ProviderCodeEqualFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEqualFold(FieldProviderCode, v))
}

// ProviderCodeContainsFold applies the ContainsFold predicate on the "provider_code" field.
func ProviderCodeContainsFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContainsFold(FieldProviderCode, v))
}

// ProviderTypeEQ applies the EQ predicate on the "provider_type" field.
func ProviderTypeEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldProviderType, v))
}

// ProviderTypeNEQ applies the NEQ predicate on the "provider_type" field.
func ProviderTypeNEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldProviderType, v))
}

// ProviderTypeIn applies the In predicate on the "provider_type" field.
func ProviderTypeIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldProviderType, vs...))
}

// ProviderTypeNotIn applies the NotIn predicate on the "provider_type" field.
func ProviderTypeNotIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldProviderType, vs...))
}

// ProviderTypeGT applies the GT predicate on the "provider_type" field.
func ProviderTypeGT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldProviderType, v))
}

// ProviderTypeGTE applies the GTE predicate on the "provider_type" field.
func ProviderTypeGTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldProviderType, v))
}

// ProviderTypeLT applies the LT predicate on the "provider_type" field.
func ProviderTypeLT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldProviderType, v))
}

// ProviderTypeLTE applies the LTE predicate on the "provider_type" field.
func ProviderTypeLTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldProviderType, v))
}

// ProviderTypeContains applies the Contains predicate on the "provider_type" field.
func ProviderTypeContains(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContains(FieldProviderType, v))
}

// ProviderTypeHasPrefix applies the HasPrefix predicate on the "provider_type" field.
func ProviderTypeHasPrefix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasPrefix(FieldProviderType, v))
}

// ProviderTypeHasSuffix applies the HasSuffix predicate on the "provider_type" field.
func ProviderTypeHasSuffix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasSuffix(FieldProviderType, v))
}

// ProviderTypeEqualFold applies the EqualFold predicate on the "provider_type" field.
func ProviderTypeEqualFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEqualFold(FieldProviderType, v))
}

// ProviderTypeContainsFold applies the ContainsFold predicate on the "provider_type" field.
func ProviderTypeContainsFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContainsFold(FieldProviderType, v))
}

// AuthConfigEncryptedEQ applies the EQ predicate on the "auth_config_encrypted" field.
func AuthConfigEncryptedEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldAuthConfigEncrypted, v))
}

// AuthConfigEncryptedNEQ applies the NEQ predicate on the "auth_config_encrypted" field.
func AuthConfigEncryptedNEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldAuthConfigEncrypted, v))
}

// AuthConfigEncryptedIn applies the In predicate on the "auth_config_encrypted" field.
func AuthConfigEncryptedIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldAuthConfigEncrypted, vs...))
}

// AuthConfigEncryptedNotIn applies the NotIn predicate on the "auth_config_encrypted" field.
func AuthConfigEncryptedNotIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldAuthConfigEncrypted, vs...))
}

// AuthConfigEncryptedGT applies the GT predicate on the "auth_config_encrypted" field.
func AuthConfigEncryptedGT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldAuthConfigEncrypted, v))
}

// AuthConfigEncryptedGTE applies the GTE predicate on the "auth_config_encrypted" field.
func AuthConfigEncryptedGTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldAuthConfigEncrypted, v))
}

// AuthConfigEncryptedLT applies the LT predicate on the "auth_config_encrypted" field.
func AuthConfigEncryptedLT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldAuthConfigEncrypted, v))
}

// AuthConfigEncryptedLTE applies the LTE predicate on the "auth_config_encrypted" field.
func AuthConfigEncryptedLTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldAuthConfigEncrypted, v))
}

// AuthConfigEncryptedContains applies the Contains predicate on the "auth_config_encrypted" field.
func AuthConfigEncryptedContains(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContains(FieldAuthConfigEncrypted, v))
}

// AuthConfigEncryptedHasPrefix applies the HasPrefix predicate on the "auth_config_encrypted" field.
func AuthConfigEncryptedHasPrefix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasPrefix(FieldAuthConfigEncrypted, v))
}

// AuthConfigEncryptedHasSuffix applies the HasSuffix predicate on the "auth_config_encrypted" field.
func AuthConfigEncryptedHasSuffix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasSuffix(FieldAuthConfigEncrypted, v))
}

// AuthConfigEncryptedEqualFold applies the EqualFold predicate on the "auth_config_encrypted" field.
func AuthConfigEncryptedEqualFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEqualFold(FieldAuthConfigEncrypted, v))
}

// AuthConfigEncryptedContainsFold applies the ContainsFold predicate on the "auth_config_encrypted" field.
func AuthConfigEncryptedContainsFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContainsFold(FieldAuthConfigEncrypted, v))
}

// HealthStatusEQ applies the EQ predicate on the "health_status" field.
func HealthStatusEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldHealthStatus, v))
}

// HealthStatusNEQ applies the NEQ predicate on the "health_status" field.
func HealthStatusNEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldHealthStatus, v))
}

// HealthStatusIn applies the In predicate on the "health_status" field.
func HealthStatusIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldHealthStatus, vs...))
}

// HealthStatusNotIn applies the NotIn predicate on the "health_status" field.
func HealthStatusNotIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldHealthStatus, vs...))
}

// HealthStatusGT applies the GT predicate on the "health_status" field.
func HealthStatusGT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldHealthStatus, v))
}

// HealthStatusGTE applies the GTE predicate on the "health_status" field.
func HealthStatusGTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldHealthStatus, v))
}

// HealthStatusLT applies the LT predicate on the "health_status" field.
func HealthStatusLT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldHealthStatus, v))
}

// HealthStatusLTE applies the LTE predicate on the "health_status" field.
func HealthStatusLTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldHealthStatus, v))
}

// HealthStatusContains applies the Contains predicate on the "health_status" field.
func HealthStatusContains(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContains(FieldHealthStatus, v))
}

// HealthStatusHasPrefix applies the HasPrefix predicate on the "health_status" field.
func HealthStatusHasPrefix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasPrefix(FieldHealthStatus, v))
}

// HealthStatusHasSuffix applies the HasSuffix predicate on the "health_status" field.
func HealthStatusHasSuffix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasSuffix(FieldHealthStatus, v))
}

// HealthStatusEqualFold applies the EqualFold predicate on the "health_status" field.
func HealthStatusEqualFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEqualFold(FieldHealthStatus, v))
}

// HealthStatusContainsFold applies the ContainsFold predicate on the "health_status" field.
func HealthStatusContainsFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContainsFold(FieldHealthStatus, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldEnabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelProvider) predicate.ModelProvider {
	return predicate.ModelProvider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelProvider) predicate.ModelProvider {
	return predicate.ModelProvider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelProvider) predicate.ModelProvider {
	return predicate.ModelProvider(sql.NotPredicates(p))
}
