// Code generated by ent, DO NOT EDIT.

package subscriptionplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the subscriptionplan type in the database.
	Label = "subscription_plan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPlanCode holds the string denoting the plan_code field in the database.
	FieldPlanCode = "plan_code"
	// FieldPlanName holds the string denoting the plan_name field in the database.
	FieldPlanName = "plan_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPriceCny holds the string denoting the price_cny field in the database.
	FieldPriceCny = "price_cny"
	// FieldPoints holds the string denoting the points field in the database.
	FieldPoints = "points"
	// FieldBonusPoints holds the string denoting the bonus_points field in the database.
	FieldBonusPoints = "bonus_points"
	// FieldDurationDays holds the string denoting the duration_days field in the database.
	FieldDurationDays = "duration_days"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// Table holds the table name of the subscriptionplan in the database.
	Table = "subscription_plans"
)

// Columns holds all SQL columns for subscriptionplan fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPlanCode,
	FieldPlanName,
	FieldStatus,
	FieldPriceCny,
	FieldPoints,
	FieldBonusPoints,
	FieldDurationDays,
	FieldCurrency,
	FieldDescription,
	FieldSortOrder,
	FieldMetadata,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PlanCodeValidator is a validator for the "plan_code" field. It is called by the builders before save.
	PlanCodeValidator func(string) error
	// PlanNameValidator is a validator for the "plan_name" field. It is called by the builders before save.
	PlanNameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultPriceCny holds the default value on creation for the "price_cny" field.
	DefaultPriceCny string
	// DefaultPoints holds the default value on creation for the "points" field.
	DefaultPoints string
	// DefaultBonusPoints holds the default value on creation for the "bonus_points" field.
	DefaultBonusPoints string
	// DefaultDurationDays holds the default value on creation for the "duration_days" field.
	DefaultDurationDays int
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
)

// OrderOption defines the ordering options for the SubscriptionPlan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPlanCode orders the results by the plan_code field.
func ByPlanCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanCode, opts...).ToFunc()
}

// ByPlanName orders the results by the plan_name field.
func ByPlanName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPriceCny orders the results by the price_cny field.
func ByPriceCny(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceCny, opts...).ToFunc()
}

// ByPoints orders the results by the points field.
func ByPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoints, opts...).ToFunc()
}

// ByBonusPoints orders the results by the bonus_points field.
func ByBonusPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBonusPoints, opts...).ToFunc()
}

// ByDurationDays orders the results by the duration_days field.
func ByDurationDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationDays, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}
