// Code generated by ent, DO NOT EDIT.

package walletgrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldUserID, v))
}

// GrantType applies equality check predicate on the "grant_type" field. It's identical to GrantTypeEQ.
func GrantType(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldGrantType, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldSourceType, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldSourceID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldStatus, v))
}

// TotalPoints applies equality check predicate on the "total_points" field. It's identical to TotalPointsEQ.
func TotalPoints(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldTotalPoints, v))
}

// AvailablePoints applies equality check predicate on the "available_points" field. It's identical to AvailablePointsEQ.
func AvailablePoints(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldAvailablePoints, v))
}

// FrozenPoints applies equality check predicate on the "frozen_points" field. It's identical to FrozenPointsEQ.
func FrozenPoints(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldFrozenPoints, v))
}

// ConsumedPoints applies equality check predicate on the "consumed_points" field. It's identical to ConsumedPointsEQ.
func ConsumedPoints(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldConsumedPoints, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLTE(FieldUserID, v))
}

// GrantTypeEQ applies the EQ predicate on the "grant_type" field.
func GrantTypeEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldGrantType, v))
}

// GrantTypeNEQ applies the NEQ predicate on the "grant_type" field.
func GrantTypeNEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNEQ(FieldGrantType, v))
}

// GrantTypeIn applies the In predicate on the "grant_type" field.
func GrantTypeIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIn(FieldGrantType, vs...))
}

// GrantTypeNotIn applies the NotIn predicate on the "grant_type" field.
func GrantTypeNotIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotIn(FieldGrantType, vs...))
}

// GrantTypeGT applies the GT predicate on the "grant_type" field.
func GrantTypeGT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGT(FieldGrantType, v))
}

// GrantTypeGTE applies the GTE predicate on the "grant_type" field.
func GrantTypeGTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGTE(FieldGrantType, v))
}

// GrantTypeLT applies the LT predicate on the "grant_type" field.
func GrantTypeLT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLT(FieldGrantType, v))
}

// GrantTypeLTE applies the LTE predicate on the "grant_type" field.
func GrantTypeLTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLTE(FieldGrantType, v))
}

// GrantTypeContains applies the Contains predicate on the "grant_type" field.
func GrantTypeContains(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContains(FieldGrantType, v))
}

// GrantTypeHasPrefix applies the HasPrefix predicate on the "grant_type" field.
func GrantTypeHasPrefix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasPrefix(FieldGrantType, v))
}

// GrantTypeHasSuffix applies the HasSuffix predicate on the "grant_type" field.
func GrantTypeHasSuffix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasSuffix(FieldGrantType, v))
}

// GrantTypeEqualFold applies the EqualFold predicate on the "grant_type" field.
func GrantTypeEqualFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEqualFold(FieldGrantType, v))
}

// GrantTypeContainsFold applies the ContainsFold predicate on the "grant_type" field.
func GrantTypeContainsFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContainsFold(FieldGrantType, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int64) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDIsNil applies the IsNil predicate on the "source_id" field.
func SourceIDIsNil() predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIsNull(FieldSourceID))
}

// SourceIDNotNil applies the NotNil predicate on the "source_id" field.
func SourceIDNotNil() predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotNull(FieldSourceID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContainsFold(FieldStatus, v))
}

// TotalPointsEQ applies the EQ predicate on the "total_points" field.
func TotalPointsEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldTotalPoints, v))
}

// TotalPointsNEQ applies the NEQ predicate on the "total_points" field.
func TotalPointsNEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNEQ(FieldTotalPoints, v))
}

// TotalPointsIn applies the In predicate on the "total_points" field.
func TotalPointsIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIn(FieldTotalPoints, vs...))
}

// TotalPointsNotIn applies the NotIn predicate on the "total_points" field.
func TotalPointsNotIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotIn(FieldTotalPoints, vs...))
}

// TotalPointsGT applies the GT predicate on the "total_points" field.
func TotalPointsGT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGT(FieldTotalPoints, v))
}

// TotalPointsGTE applies the GTE predicate on the "total_points" field.
func TotalPointsGTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGTE(FieldTotalPoints, v))
}

// TotalPointsLT applies the LT predicate on the "total_points" field.
func TotalPointsLT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLT(FieldTotalPoints, v))
}

// TotalPointsLTE applies the LTE predicate on the "total_points" field.
func TotalPointsLTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLTE(FieldTotalPoints, v))
}

// TotalPointsContains applies the Contains predicate on the "total_points" field.
func TotalPointsContains(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContains(FieldTotalPoints, v))
}

// TotalPointsHasPrefix applies the HasPrefix predicate on the "total_points" field.
func TotalPointsHasPrefix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasPrefix(FieldTotalPoints, v))
}

// TotalPointsHasSuffix applies the HasSuffix predicate on the "total_points" field.
func TotalPointsHasSuffix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasSuffix(FieldTotalPoints, v))
}

// TotalPointsEqualFold applies the EqualFold predicate on the "total_points" field.
func TotalPointsEqualFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEqualFold(FieldTotalPoints, v))
}

// TotalPointsContainsFold applies the ContainsFold predicate on the "total_points" field.
func TotalPointsContainsFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContainsFold(FieldTotalPoints, v))
}

// AvailablePointsEQ applies the EQ predicate on the "available_points" field.
func AvailablePointsEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldAvailablePoints, v))
}

// AvailablePointsNEQ applies the NEQ predicate on the "available_points" field.
func AvailablePointsNEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNEQ(FieldAvailablePoints, v))
}

// AvailablePointsIn applies the In predicate on the "available_points" field.
func AvailablePointsIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIn(FieldAvailablePoints, vs...))
}

// AvailablePointsNotIn applies the NotIn predicate on the "available_points" field.
func AvailablePointsNotIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotIn(FieldAvailablePoints, vs...))
}

// AvailablePointsGT applies the GT predicate on the "available_points" field.
func AvailablePointsGT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGT(FieldAvailablePoints, v))
}

// AvailablePointsGTE applies the GTE predicate on the "available_points" field.
func AvailablePointsGTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGTE(FieldAvailablePoints, v))
}

// AvailablePointsLT applies the LT predicate on the "available_points" field.
func AvailablePointsLT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLT(FieldAvailablePoints, v))
}

// AvailablePointsLTE applies the LTE predicate on the "available_points" field.
func AvailablePointsLTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLTE(FieldAvailablePoints, v))
}

// AvailablePointsContains applies the Contains predicate on the "available_points" field.
func AvailablePointsContains(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContains(FieldAvailablePoints, v))
}

// AvailablePointsHasPrefix applies the HasPrefix predicate on the "available_points" field.
func AvailablePointsHasPrefix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasPrefix(FieldAvailablePoints, v))
}

// AvailablePointsHasSuffix applies the HasSuffix predicate on the "available_points" field.
func AvailablePointsHasSuffix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasSuffix(FieldAvailablePoints, v))
}

// AvailablePointsEqualFold applies the EqualFold predicate on the "available_points" field.
func AvailablePointsEqualFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEqualFold(FieldAvailablePoints, v))
}

// AvailablePointsContainsFold applies the ContainsFold predicate on the "available_points" field.
func AvailablePointsContainsFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContainsFold(FieldAvailablePoints, v))
}

// FrozenPointsEQ applies the EQ predicate on the "frozen_points" field.
func FrozenPointsEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldFrozenPoints, v))
}

// FrozenPointsNEQ applies the NEQ predicate on the "frozen_points" field.
func FrozenPointsNEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNEQ(FieldFrozenPoints, v))
}

// FrozenPointsIn applies the In predicate on the "frozen_points" field.
func FrozenPointsIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIn(FieldFrozenPoints, vs...))
}

// FrozenPointsNotIn applies the NotIn predicate on the "frozen_points" field.
func FrozenPointsNotIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotIn(FieldFrozenPoints, vs...))
}

// FrozenPointsGT applies the GT predicate on the "frozen_points" field.
func FrozenPointsGT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGT(FieldFrozenPoints, v))
}

// FrozenPointsGTE applies the GTE predicate on the "frozen_points" field.
func FrozenPointsGTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGTE(FieldFrozenPoints, v))
}

// FrozenPointsLT applies the LT predicate on the "frozen_points" field.
func FrozenPointsLT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLT(FieldFrozenPoints, v))
}

// FrozenPointsLTE applies the LTE predicate on the "frozen_points" field.
func FrozenPointsLTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLTE(FieldFrozenPoints, v))
}

// FrozenPointsContains applies the Contains predicate on the "frozen_points" field.
func FrozenPointsContains(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContains(FieldFrozenPoints, v))
}

// FrozenPointsHasPrefix applies the HasPrefix predicate on the "frozen_points" field.
func FrozenPointsHasPrefix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasPrefix(FieldFrozenPoints, v))
}

// FrozenPointsHasSuffix applies the HasSuffix predicate on the "frozen_points" field.
func FrozenPointsHasSuffix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasSuffix(FieldFrozenPoints, v))
}

// FrozenPointsEqualFold applies the EqualFold predicate on the "frozen_points" field.
func FrozenPointsEqualFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEqualFold(FieldFrozenPoints, v))
}

// FrozenPointsContainsFold applies the ContainsFold predicate on the "frozen_points" field.
func FrozenPointsContainsFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContainsFold(FieldFrozenPoints, v))
}

// ConsumedPointsEQ applies the EQ predicate on the "consumed_points" field.
func ConsumedPointsEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldConsumedPoints, v))
}

// ConsumedPointsNEQ applies the NEQ predicate on the "consumed_points" field.
func ConsumedPointsNEQ(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNEQ(FieldConsumedPoints, v))
}

// ConsumedPointsIn applies the In predicate on the "consumed_points" field.
func ConsumedPointsIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIn(FieldConsumedPoints, vs...))
}

// ConsumedPointsNotIn applies the NotIn predicate on the "consumed_points" field.
func ConsumedPointsNotIn(vs ...string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotIn(FieldConsumedPoints, vs...))
}

// ConsumedPointsGT applies the GT predicate on the "consumed_points" field.
func ConsumedPointsGT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGT(FieldConsumedPoints, v))
}

// ConsumedPointsGTE applies the GTE predicate on the "consumed_points" field.
func ConsumedPointsGTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGTE(FieldConsumedPoints, v))
}

// ConsumedPointsLT applies the LT predicate on the "consumed_points" field.
func ConsumedPointsLT(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLT(FieldConsumedPoints, v))
}

// ConsumedPointsLTE applies the LTE predicate on the "consumed_points" field.
func ConsumedPointsLTE(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLTE(FieldConsumedPoints, v))
}

// ConsumedPointsContains applies the Contains predicate on the "consumed_points" field.
func ConsumedPointsContains(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContains(FieldConsumedPoints, v))
}

// ConsumedPointsHasPrefix applies the HasPrefix predicate on the "consumed_points" field.
func ConsumedPointsHasPrefix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasPrefix(FieldConsumedPoints, v))
}

// ConsumedPointsHasSuffix applies the HasSuffix predicate on the "consumed_points" field.
func ConsumedPointsHasSuffix(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldHasSuffix(FieldConsumedPoints, v))
}

// ConsumedPointsEqualFold applies the EqualFold predicate on the "consumed_points" field.
func ConsumedPointsEqualFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEqualFold(FieldConsumedPoints, v))
}

// ConsumedPointsContainsFold applies the ContainsFold predicate on the "consumed_points" field.
func ConsumedPointsContainsFold(v string) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldContainsFold(FieldConsumedPoints, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotNull(FieldExpiresAt))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.WalletGrant {
	return predicate.WalletGrant(sql.FieldNotNull(FieldMetadata))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WalletGrant) predicate.WalletGrant {
	return predicate.WalletGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WalletGrant) predicate.WalletGrant {
	return predicate.WalletGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WalletGrant) predicate.WalletGrant {
	return predicate.WalletGrant(sql.NotPredicates(p))
}
