// Code generated by ent, DO NOT EDIT.

package secureconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the secureconfig type in the database.
	Label = "secure_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldConfigCategory holds the string denoting the config_category field in the database.
	FieldConfigCategory = "config_category"
	// FieldConfigKey holds the string denoting the config_key field in the database.
	FieldConfigKey = "config_key"
	// FieldPublicValue holds the string denoting the public_value field in the database.
	FieldPublicValue = "public_value"
	// FieldSecretEncrypted holds the string denoting the secret_encrypted field in the database.
	FieldSecretEncrypted = "secret_encrypted"
	// FieldSecretFingerprint holds the string denoting the secret_fingerprint field in the database.
	FieldSecretFingerprint = "secret_fingerprint"
	// FieldSecretFields holds the string denoting the secret_fields field in the database.
	FieldSecretFields = "secret_fields"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// Table holds the table name of the secureconfig in the database.
	Table = "secure_configs"
)

// Columns holds all SQL columns for secureconfig fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldConfigCategory,
	FieldConfigKey,
	FieldPublicValue,
	FieldSecretEncrypted,
	FieldSecretFingerprint,
	FieldSecretFields,
	FieldVersion,
	FieldUpdatedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ConfigCategoryValidator is a validator for the "config_category" field. It is called by the builders before save.
	ConfigCategoryValidator func(string) error
	// ConfigKeyValidator is a validator for the "config_key" field. It is called by the builders before save.
	ConfigKeyValidator func(string) error
	// DefaultSecretFingerprint holds the default value on creation for the "secret_fingerprint" field.
	DefaultSecretFingerprint string
	// SecretFingerprintValidator is a validator for the "secret_fingerprint" field. It is called by the builders before save.
	SecretFingerprintValidator func(string) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int64
	// DefaultUpdatedBy holds the default value on creation for the "updated_by" field.
	DefaultUpdatedBy int64
)

// OrderOption defines the ordering options for the SecureConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByConfigCategory orders the results by the config_category field.
func ByConfigCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigCategory, opts...).ToFunc()
}

// ByConfigKey orders the results by the config_key field.
func ByConfigKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigKey, opts...).ToFunc()
}

// BySecretFingerprint orders the results by the secret_fingerprint field.
func BySecretFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretFingerprint, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}
