// Code generated by ent, DO NOT EDIT.

package secureconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fatballfish/pic-gallery/internal/repository/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// ConfigCategory applies equality check predicate on the "config_category" field. It's identical to ConfigCategoryEQ.
func ConfigCategory(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldConfigCategory, v))
}

// ConfigKey applies equality check predicate on the "config_key" field. It's identical to ConfigKeyEQ.
func ConfigKey(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldConfigKey, v))
}

// SecretFingerprint applies equality check predicate on the "secret_fingerprint" field. It's identical to SecretFingerprintEQ.
func SecretFingerprint(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldSecretFingerprint, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldVersion, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// ConfigCategoryEQ applies the EQ predicate on the "config_category" field.
func ConfigCategoryEQ(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldConfigCategory, v))
}

// ConfigCategoryNEQ applies the NEQ predicate on the "config_category" field.
func ConfigCategoryNEQ(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNEQ(FieldConfigCategory, v))
}

// ConfigCategoryIn applies the In predicate on the "config_category" field.
func ConfigCategoryIn(vs ...string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldIn(FieldConfigCategory, vs...))
}

// ConfigCategoryNotIn applies the NotIn predicate on the "config_category" field.
func ConfigCategoryNotIn(vs ...string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNotIn(FieldConfigCategory, vs...))
}

// ConfigCategoryGT applies the GT predicate on the "config_category" field.
func ConfigCategoryGT(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGT(FieldConfigCategory, v))
}

// ConfigCategoryGTE applies the GTE predicate on the "config_category" field.
func ConfigCategoryGTE(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGTE(FieldConfigCategory, v))
}

// ConfigCategoryLT applies the LT predicate on the "config_category" field.
func ConfigCategoryLT(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLT(FieldConfigCategory, v))
}

// ConfigCategoryLTE applies the LTE predicate on the "config_category" field.
func ConfigCategoryLTE(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLTE(FieldConfigCategory, v))
}

// ConfigCategoryContains applies the Contains predicate on the "config_category" field.
func ConfigCategoryContains(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldContains(FieldConfigCategory, v))
}

// ConfigCategoryHasPrefix applies the HasPrefix predicate on the "config_category" field.
func ConfigCategoryHasPrefix(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldHasPrefix(FieldConfigCategory, v))
}

// ConfigCategoryHasSuffix applies the HasSuffix predicate on the "config_category" field.
func ConfigCategoryHasSuffix(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldHasSuffix(FieldConfigCategory, v))
}

// ConfigCategoryEqualFold applies the EqualFold predicate on the "config_category" field.
func ConfigCategoryEqualFold(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEqualFold(FieldConfigCategory, v))
}

// ConfigCategoryContainsFold applies the ContainsFold predicate on the "config_category" field.
func ConfigCategoryContainsFold(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldContainsFold(FieldConfigCategory, v))
}

// ConfigKeyEQ applies the EQ predicate on the "config_key" field.
func ConfigKeyEQ(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldConfigKey, v))
}

// ConfigKeyNEQ applies the NEQ predicate on the "config_key" field.
func ConfigKeyNEQ(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNEQ(FieldConfigKey, v))
}

// ConfigKeyIn applies the In predicate on the "config_key" field.
func ConfigKeyIn(vs ...string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldIn(FieldConfigKey, vs...))
}

// ConfigKeyNotIn applies the NotIn predicate on the "config_key" field.
func ConfigKeyNotIn(vs ...string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNotIn(FieldConfigKey, vs...))
}

// ConfigKeyGT applies the GT predicate on the "config_key" field.
func ConfigKeyGT(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGT(FieldConfigKey, v))
}

// ConfigKeyGTE applies the GTE predicate on the "config_key" field.
func ConfigKeyGTE(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGTE(FieldConfigKey, v))
}

// ConfigKeyLT applies the LT predicate on the "config_key" field.
func ConfigKeyLT(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLT(FieldConfigKey, v))
}

// ConfigKeyLTE applies the LTE predicate on the "config_key" field.
func ConfigKeyLTE(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLTE(FieldConfigKey, v))
}

// ConfigKeyContains applies the Contains predicate on the "config_key" field.
func ConfigKeyContains(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldContains(FieldConfigKey, v))
}

// ConfigKeyHasPrefix applies the HasPrefix predicate on the "config_key" field.
func ConfigKeyHasPrefix(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldHasPrefix(FieldConfigKey, v))
}

// ConfigKeyHasSuffix applies the HasSuffix predicate on the "config_key" field.
func ConfigKeyHasSuffix(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldHasSuffix(FieldConfigKey, v))
}

// ConfigKeyEqualFold applies the EqualFold predicate on the "config_key" field.
func ConfigKeyEqualFold(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEqualFold(FieldConfigKey, v))
}

// ConfigKeyContainsFold applies the ContainsFold predicate on the "config_key" field.
func ConfigKeyContainsFold(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldContainsFold(FieldConfigKey, v))
}

// PublicValueIsNil applies the IsNil predicate on the "public_value" field.
func PublicValueIsNil() predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldIsNull(FieldPublicValue))
}

// PublicValueNotNil applies the NotNil predicate on the "public_value" field.
func PublicValueNotNil() predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNotNull(FieldPublicValue))
}

// SecretEncryptedIsNil applies the IsNil predicate on the "secret_encrypted" field.
func SecretEncryptedIsNil() predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldIsNull(FieldSecretEncrypted))
}

// SecretEncryptedNotNil applies the NotNil predicate on the "secret_encrypted" field.
func SecretEncryptedNotNil() predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNotNull(FieldSecretEncrypted))
}

// SecretFingerprintEQ applies the EQ predicate on the "secret_fingerprint" field.
func SecretFingerprintEQ(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldSecretFingerprint, v))
}

// SecretFingerprintNEQ applies the NEQ predicate on the "secret_fingerprint" field.
func SecretFingerprintNEQ(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNEQ(FieldSecretFingerprint, v))
}

// SecretFingerprintIn applies the In predicate on the "secret_fingerprint" field.
func SecretFingerprintIn(vs ...string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldIn(FieldSecretFingerprint, vs...))
}

// SecretFingerprintNotIn applies the NotIn predicate on the "secret_fingerprint" field.
func SecretFingerprintNotIn(vs ...string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNotIn(FieldSecretFingerprint, vs...))
}

// SecretFingerprintGT applies the GT predicate on the "secret_fingerprint" field.
func SecretFingerprintGT(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGT(FieldSecretFingerprint, v))
}

// SecretFingerprintGTE applies the GTE predicate on the "secret_fingerprint" field.
func SecretFingerprintGTE(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGTE(FieldSecretFingerprint, v))
}

// SecretFingerprintLT applies the LT predicate on the "secret_fingerprint" field.
func SecretFingerprintLT(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLT(FieldSecretFingerprint, v))
}

// SecretFingerprintLTE applies the LTE predicate on the "secret_fingerprint" field.
func SecretFingerprintLTE(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLTE(FieldSecretFingerprint, v))
}

// SecretFingerprintContains applies the Contains predicate on the "secret_fingerprint" field.
func SecretFingerprintContains(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldContains(FieldSecretFingerprint, v))
}

// SecretFingerprintHasPrefix applies the HasPrefix predicate on the "secret_fingerprint" field.
func SecretFingerprintHasPrefix(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldHasPrefix(FieldSecretFingerprint, v))
}

// SecretFingerprintHasSuffix applies the HasSuffix predicate on the "secret_fingerprint" field.
func SecretFingerprintHasSuffix(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldHasSuffix(FieldSecretFingerprint, v))
}

// SecretFingerprintEqualFold applies the EqualFold predicate on the "secret_fingerprint" field.
func SecretFingerprintEqualFold(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEqualFold(FieldSecretFingerprint, v))
}

// SecretFingerprintContainsFold applies the ContainsFold predicate on the "secret_fingerprint" field.
func SecretFingerprintContainsFold(v string) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldContainsFold(FieldSecretFingerprint, v))
}

// SecretFieldsIsNil applies the IsNil predicate on the "secret_fields" field.
func SecretFieldsIsNil() predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldIsNull(FieldSecretFields))
}

// SecretFieldsNotNil applies the NotNil predicate on the "secret_fields" field.
func SecretFieldsNotNil() predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNotNull(FieldSecretFields))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLTE(FieldVersion, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.SecureConfig {
	return predicate.SecureConfig(sql.FieldLTE(FieldUpdatedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SecureConfig) predicate.SecureConfig {
	return predicate.SecureConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SecureConfig) predicate.SecureConfig {
	return predicate.SecureConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SecureConfig) predicate.SecureConfig {
	return predicate.SecureConfig(sql.NotPredicates(p))
}
